baseURL = "https://disic.github.io/gazette-bluehats/"
languageCode = "fr-Fr"
title = "Gazette #BlueHats"
copyright = "Direction interministérielle du numérique"
defaultContentLanguage = "fr"
publishDir = "docs"

[Author]
    name = "Gazette #BlueHats - La gazette du logiciel libre dans/pour l'administration"
    profile = "https://disic.github.io/gazette-bluehats"

[Taxonomies]
    tag = "tags"
    category = "categories"

[languages]
  [languages.fr]
    weight = 1
    [languages.fr.params]
        headline = "Gazette #BlueHats"
        description = "La gazette du logiciel libre dans/pour l'administration"
  [languages.en]
    weight = 2
    [languages.en.params]
        headline = "Gazette #BlueHats"
        description = "La gazette du logiciel libre dans/pour l'administration"

[Params]
    intro = true
    headline = "Gazette #BlueHats"
    github = "https://github.com/disic/gazette-bluehats"
    twitter = "https://twitter.com/_DINUM"
    email = "bluehats@etalab.gouv.fr"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon 2 Jan 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:filename"

[[languages.fr.menu.main]]
    name = "À propos"
    url = "/a-propos/"
    weight = 1

[minify]
    disableCSS = false
    disableHTML = false
    disableJS = false
    disableJSON = false
    disableSVG = false
    disableXML = false
    minifyOutput = true
