baseURL = "https://disic.github.io/gazette-bluehats/"
languageCode = "fr-Fr"
title = "Gazette #BlueHats"
copyright = "Direction interministérielle du numérique"
defaultContentLanguage = "fr"
publishDir = "docs"

[Author]
    name = "Gazette #BlueHats - La gazette du logiciel libre dans/pour l'administration"
    profile = "https://disic.github.io/gazette-bluehats"

[Taxonomies]
    tag = "tags"
    category = "categories"

[languages]
  [languages.fr]
    weight = 1
    [languages.fr.params]
        headline = "Gazette #BlueHats"
        description = "La gazette du logiciel libre dans/pour l'administration"
  [languages.en]
    weight = 2
    [languages.en.params]
        headline = "Gazette #BlueHats"
        description = "La gazette du logiciel libre dans/pour l'administration"

[Params]
    intro = true
    headline = "Gazette #BlueHats"
    github = "https://github.com/disic/gazette-bluehats"
    # gitlab = ""
    twitter = "https://twitter.com/_DINUM"
    # mastodon = "https://mastodon.etalab.gouv.fr/@bzg"
    # stackoverflow = "https://stackoverflow.com/users/1037678/bzg"
    email = "bluehats@etalab.gouv.fr"
    opengraph = true
    shareTwitter = true
    shareFacebook = false
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon 2 Jan 2006"
    highlightJsUrl = ""
    highlightJsLocalUrl = ""

[Permalinks]
    post = "/:filename.html"

[[languages.fr.menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 1

# [[languages.fr.menu.main]]
#     name = "English"
#     url = "/en/"
#     weight = 5

# [[languages.en.menu.main]]
#     name = "About"
#     url = "/en/about/"
#     weight = 1

# [[languages.en.menu.main]]
#     name = "Français"
#     url = "/"
#     weight = 4
