#+title: Gazette #BlueHats n°12
#+date: 2021-08-24
#+author: DINUM
#+layout: post
#+draft: false
#+options: toc:nil num:nil H:4 ^:nil pri:t html-postamble:nil html-preamble:nil
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

#+begin_center
La gazette [[https://disic.github.io/gazette-bluehats/][#BlueHats]] est une lettre d'information bimestrielle sur le
logiciel libre dans, par et pour l'administration publique. Cette
gazette est la contribution de la [[https://www.numerique.gouv.fr/][DINUM]] au mouvement des #BlueHats,
les hackers d'intérêt général.

Vous pouvez vous y inscrire [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][depuis ce lien]], [[https://disic.github.io/gazette-bluehats/][lire les gazettes
précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]] pour les prochaines éditions.

Pour accéder à la version en ligne, [[https://disic.github.io/gazette-bluehats/gazette_bluehat_12/][cliquez ici]].  Bonne lecture !
-----
#+end_center

Pour cette gazette estivale, nous vous proposons deux « focus tech »,
une surprise, deux offres d'emploi pour travailler sur des logiciels
libres dans l'administration publique, une belle série d'événements
(vous ne pourrez pas participer à tous) et notre habituelle revue de
presse.  Bonne lecture !

* Focus tech

** Trombi, un trombinoscope simple connecté à un LDAP

Théo Lechémia, développeur au [[https://github.com/PnEcrins][Parc national des Écrins]], a réalisé une
application web en Python + VueJS qui permet de mettre en place
facilement un trombinoscope basé sur un LDAP.  L'application est
générique et publiée sous licence libre GPLv3.

- Elle doit être connectée à un serveur LDAP pour lister les
  utilisateurs, leur description, leur service, leurs téléphones et
  leur email

- Elle permet aussi d'afficher l'agenda de chaque utilisateur en se
  connectant à un agenda compatible iCalendar/CALDAV.

- Les photos de chaque utilisateur ne sont pas stockées dans l'AD,
  mais dans les répertoires de l'application.

- Par défaut, tous les utilisateurs peuvent ajouter ou modifier la
  photo d'un utilisateur directement depuis sa fiche, pour faciliter
  l'administration de l'outil.

=>>= Détails, documentation et code source disponibles sur [[https://github.com/PnEcrins/Trombi]].

** La DGFiP développe une version libre d'Hortonworks

/Une contribution de Su Yang, responsable du pôle données chez Direction générale des Finances publiques./

Le « Pôle de données » de la DGFIP, créé depuis janvier 2021, a pour
ambition d'industrialiser la valorisation des données.  Pour ce faire
il est organisé en quatre verticales d'activités : il met en place un
lac de données avec des données métiers provenant de différents silos.
Ce lac de données s'appuie sur une distribution Hadoop : la version
Hortonworks 3.1.4, qui est en production depuis mars 2021.  

Le pôle accompagne et participe à des projets data (datascience,
dataviz, etc.) et anime les profils données qui y contribuent ; il met
en place la gouvernance des données qui contribue à la connaissance et
la qualité des données et la conformité réglementaire des projets
associés ; et il gère l'échange des données via des APIs (internes ou
externes) ou en Open Data.

Le rachat par Cloudera de la distribution libre Hortonworks, et par la
suite l'annonce de la fin de l'évolution de la solution Open Source
font émerger un choix, entre (1) acheter une solution Cloudera au prix
élevé, potentiellement en millions d'euros annuels ou (2) développer
sa propre solution libre en s'associant à d'autres acteurs.

C'est cette dernière option qui a été retenue par la DGFIP, qui, pour
ce faire, a recruté des spécialistes pointus.  Cette démarche
s'effectue en commun avec d'autres grands groupes et les 2 premiers
lots prévus pour T4 2021 et T1 2022 permettront un premier niveau
d'indépendance.

Ce retour d'expérience répond notamment aux questions concernant le
besoin à couvrir, les raisons du choix de développer une solution
propre, le soutien de l'éco-système Open source, les avantages de la
solution retenue en fonction des critères de la DGFIP.

* BlueHats Summer of Code 2022

Vous êtes une administration ?  Vous utilisez un logiciel libre auquel
vous souhaitez contribuer ?  Vous êtes prête à accueillir /gratuitement/
un étudiant d'une grande école d'ingénieurs pour qu'il travaille sur
cette contribution avec la communauté du projet libre ?  Écrivez-nous
à [[mailto:bluehats@etalab.gouv.fr][bluehats@etalab.gouv.fr]] en indiquant en quelques lignes le projet
que vous envisagez !  La DINUM lancera un appel à projet public dans
les semaines qui viennent, mais il n'est pas trop tôt pour nous faire
part de vos idées.

* Offres d'emploi

La [[https://lafabriquedesmobilites.fr/][Fabrique des mobilités]] recrute une ou un développeur front sur le
sujet du Coach CO2.  Il s'agit de construire un logiciel libre qui
complétera le logiciel [[https://forge.grandlyon.com/pocs/cozy/tracemob][Tracemob]] pour en visualiser les données sous
l'angle de l'empreinte climat de notre mobilité. Tout le code sera
libre.
 
=>>= Plus d'infos ici : [[https://pad.fabmob.io/fiche-poste-coach-co2]]

Le projet [[https://archifiltre.fabrique.social.gouv.fr/][Archifiltre]] recrute un développeur pour se charger de mettre
en place l’outillage pour l’extraction et le traitement des archives
de messagerie au format [[https://fr.wikipedia.org/wiki/.pst][.pst]], en vue de leur analyse dans Archifiltre.

=>>= Plus d'infos ici : [[https://beta.gouv.fr/recrutement/2021/07/28/dev-archifiltre.html​]]

* Événements

- En *septembre 2021*, retrouvez [[https://github.com/blue-hats/ateliers/blob/main/ateliers.org][les ateliers BlueHats]], avec notamment
  la présentation de la messagerie collaborative de l'État, les outils
  [[https://framasoft.org][Framasoft]] dans l’administration publique ainsi qu'une présentation
  de framaforms/Yakforms, et la présentation du Standard pour un code
  informatique public ([[https://standard.publiccode.net/][lien en anglais]]).

- *9 septembre 2021* : Intervention de la DGFiP à la [[https://www.crip-asso.fr/crip/event/detail.html/idConf/966][journée annuelle
  /open source/ du CRIP]].  « Lac de données et distribution Hadoop :
  suite au rachat d’Hortonworks par Cloudera, motivations et démarche
  de la DGFIP », par Su YANG, Responsable du pôle données DGFIP.

- *4 et 5 novembre 2021* : Organisation du premier [[https://matomocamp.org][Matomocamp]] !

- *14 et 15 octobre 2021* : le *B-Boost*, le salon du logiciel libre à La
  Rochelle : plus de 30 exposants, 30 conférences, et [[https://b-boost.fr/][plus encore]].

- *14 et 15 octobre 2021* : Les rencontres [[https://geotrek.fr/][Geotrek]] à Aix-en-Provence.
  Voir [[https://groups.google.com/u/3/g/geotrek-fr/c/k3IxyRHEdsE][le programme]].  L'après-midi du premier jour sera consacrée aux
  échanges de données entre Geotrek et d'autres outils, mais aussi à
  la diffusion libre des données.

- *18, 19 et 20 octobre 2021* : Comme chaque année, l'association
  Scenari organise ses *Rencontres Scenari*.

  Scenari, c'est un ensemble de logiciels dédiés à la création
  collaborative structurée, et publication/diffusion de contenus
  multimédias et multisupports. Ils sont très utilisés dans le domaine
  de la formation et de la documentation, mais servent aussi pour
  l'audiovisuel, la qualité, ou les clés de déterminations, ...

  Les Télé-Rencontres Scenari 2021, c'est l'occasion de découvrir ces
  outils et comment ils peuvent améliorer vos contenus et vous faire
  gagner du temps dans leur création. C'est aussi l'occasion de
  connaître de nouvelles fonctionnalités et de nouveaux usages grâce à
  des ateliers et des conférences.

  Comme l'année dernière, raisons sanitaires obligent, les
  Télé-Rencontres Scenari 2021 se déroulement principalement en
  ligne : les contenus seront disponibles courant octobre et des
  sessions de visioconférence seront organisées les 18-19-20 octobre.

  Toutes les informations sont ou seront disponibles sur le site des
  Rencontres 2021 : [[https://scenari.org/rencontres2021/]]

- *9 novembre 2021* : /Save the date/ pour une journée BlueHats lors du
  salon [[https://www.opensource-experience.com/][Open Source Experience]].  Tenez-vous prêts à répondre à l'appel
  que nous enverrons pour des présentations courtes, sur le même
  format qu'en [[https://forum.etalab.gouv.fr/t/journee-bluehats-lors-du-paris-open-source-summit-le-11-decembre-2019/4614][2019]] !  Si vous avez déjà des propositions, n'hésitez
  pas à nous [[mailto:bluehats@etalab.gouv.fr][écrire]].

* Revue de presse

** Échos de l'administration

- [[https://www.numerique.gouv.fr/outils-agents/webinaire-etat/][Webinaire de l'État]] : Un service dédié aux agents de l’État pour
  leurs séminaires en ligne, formations, présentations, conférences
  virtuelles, jusqu’à 350 participants.  Sur numerique.gouv.fr,
  juin 2021.

- [[https://www.tresor.economie.gouv.fr/Articles/2021/06/30/tresthor-le-nouvel-outil-de-la-dg-tresor-pour-realiser-des-previsions-macroeconomiques][tresthor: le nouvel outil de la DG Trésor pour réaliser des
  prévisions macroéconomiques]], www.tresor.economie.gouv.fr, juin 2021.

- [[https://april.org/111-matomo][Emission « Libre à vous » de l'April]] : L'analyse d'audience de sites
  web et Matomo avec Alexandre Bulté directeur technique d'Etalab et
  Ronan Chardonneau, formateur indépendant sur Matomo.  Sur april.org,
  juin 2021.

- [[https://www.acteurspublics.fr/articles/le-gouvernement-degaine-un-nouveau-plan-daction-pour-la-science-ouverte][Le gouvernement dégaine un nouveau plan d'action pour la science
  ouverte]], acteurspublics.fr, juillet 2021.

** Sur le rapport parlementaire sur la souveraineté numérique

- [[https://www.assemblee-nationale.fr/dyn/15/rapports/souvnum/l15b4299-t1_rapport-information][Bâtir et promouvoir une souveraineté numérique nationale et
  européenne]], assemblee-nationale.fr, juillet 2021

- [[https://www.nextinpact.com/article/47722/logiciel-libres-et-health-data-hub-au-menu-rapport-sur-souverainete-numerique][Logiciel libres et Health Data Hub au menu du rapport sur la
  souveraineté du numérique]], nextinpact.com, juillet 2021

- [[https://www.nextinpact.com/lebrief/47745/le-rapport-parlementaire-sur-souverainete-numerique][Le rapport parlementaire sur la souveraineté du numérique]],
  nextinpact.com, juillet 2021

- [[https://www.zdnet.fr/blogs/l-esprit-libre/administration-un-rapport-parlementaire-prone-le-recours-systematique-au-logiciel-libre-39926175.htm][Administration: un rapport parlementaire prône le recours
  systématique au logiciel libre]], zdnet.fr, juillet 2021

- [[https://www.banquedesterritoires.fr/souverainete-numerique-des-administrations-invitees-lexemplarite][Souveraineté numérique : des administrations invitées à
  l'exemplarité]], banquedesterritoires.fr, juillet 2021.

- [[https://cnll.fr/news/mission-parlementaire-souverainete-numerique/][Le CNLL salue les propositions de la mission parlementaire sur la
  souveraineté numérique]], cnll.fr, juillet 2021

- [[https://www.acteurspublics.fr/articles/les-propositions-cles-de-la-mission-sur-la-souverainete-numerique-de-la-france][Les propositions clés de la mission sur la souveraineté numérique de
  la France]], acteurspublics.fr, juillet 2021.

** D'Europe et d'ailleurs

- [[https://www.euclidia.eu/publications/EUCLIDIA-Press.Release.Launch.Announcement][23 European Cloud Technology Companies form the European Cloud
  Industrial Alliance (EUCLIDIA)]], euclidia.eu, juillet 2021.

- [[https://openuk.uk/stateofopen/][OpenUK Report. State of Open: The UK in 2021]]

- [[https://public.digital/2021/06/21/open-source-in-government-creating-the-conditions-for-success][Open source in government: creating the conditions for success]],
  public.digital, juin 2021.

- [[https://techcrunch.com/2021/03/03/1-3m-in-grants-go-towards-making-the-webs-open-source-infrastructure-more-equitable/][$1.3M in grants go toward making the web's open-source
  infrastructure more equitable]], techcrunch.com, mars 2021.

- [[https://www.fordfoundation.org/the-latest/news/major-philanthropies-tackle-inequality-by-strengthening-how-open-source-code-is-developed-and-maintained/][Ford foundation. Major Philanthropies Tackle Inequality by
  Strengthening How Open Source Code is Developed and Maintained]],
  fordfoundation.org, mars 2021.

** Études et opinions

- [[https://hal.archives-ouvertes.fr/hal-03177060/][Framasoft : de la plateforme à l'archipel]], archives-ouvertes.fr,
  mars 2021.

- [[https://journals.openedition.org/terminal/7793][Communs numériques : une nouvelle forme d'action collective ?]] Revue
  Terminal, juin 2021

- [[http://florian.lainez.fr/2021/05/12/openstreetmap-nest-pas-une-communaute-cest-un-mouvement-politique/][OpenStreetMap n'est pas une communauté, c'est un mouvement
  politique]], florian.lainez.fr, mai 2021.

- [[https://actu.ionis-group.com/henri-verdier/][Henri Verdier: « Si les GAFAM font partie du problème, ils doivent
  faire partie de la solution »]], ionis-group.com, 2021.

- [[https://www.april.org/rapport-latombe-systematiser-le-recours-au-logiciel-libre-dans-les-administrations-un-enjeu-de-souve][Rapport Latombe : systématiser le recours au logiciel libre dans les
  administrations, un enjeu de souveraineté numérique]], april.org,
  août 2021.

