#+title: Gazette #BlueHats n°4
#+date: 2019-12-08
#+author: DINUM
#+layout: post

La gazette #BlueHats est une lettre d'information bimestrielle sur le logiciel libre dans, par et pour l'administration publique.  Cette gazette est le contribution de la DINUM au mouvement des #BlueHats, les hackers d'intérêt général.

Vous pouvez vous [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][inscrire]], [[https://github.com/DISIC/gazette-bluehats][lire les gazettes précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]].

* La journée #BlueHats au Paris Open Source Summit 2019

Les BlueHats se retrouvent demain 11 décembre au [[https://www.opensourcesummit.paris/][Paris Open Source
Summit]] pour souffler leur première bougie !

Retrouvez-nous en salles PLATEAU 1 et PLATEAU 3 pour une journée de
partage d'expérience entre administrations et d'ateliers techniques.

Tout le programme des ateliers, conférences et tables ouvertes est à
retrouver sur [[https://forum.etalab.gouv.fr/t/journee-bluehats-lors-du-paris-open-source-summit-le-11-decembre-2019/4614][cette page du forum Etalab]].

N'hésitez pas à retweeter [[https://twitter.com/_DINUM/status/1201497346804256768][l'annonce de la DINUM]].

* Focus sur des solutions libres dans l'administration

** Un framaform-like pour l'agence française pour la biodiversité

Après avoir fait une importante [[https://degooglisons-internet.org][campagne de sensibilisation]] et de
déploiement de services libres alternatifs à ceux des GAFAM,
l'association [[https://framasoft.org][Framasoft]] invite désormais les utilisateurs à déployer
leurs propres instances de ces outils (lire [[https://framablog.org/2019/09/24/deframasoftisons-internet/][cette entrée de blog]].)
L'Agence française pour la biodiversité (AFB) a ainsi déployé l'outil
libre [[https://www.drupal.org/project/webform][Drupal Webform]] sur ses serveurs pour que ses agents puissent
créer et partager des formulaires et enquêtes en ligne :
[[https://formulaires.afbiodiversite.fr]].

Il s'agit de l'outil utilisé par le service Framaforms, mais que
chacun peut installer sur ses serveurs, comme tous les [[https://degooglisons-internet.org/fr/alternatives/][autres services
de Framasoft]]. Cette solution a été mise en place dans le contexte du
RGPD et l'importance de maîtriser les données (anonymisation, règles
de conservation, etc.), tout en s'appuyant sur une communauté active
autour du libre.  L'AFB prévoie d'héberger prochainement la solution
en interne pour encore mieux la maîtriser.

L'AFB utilise d'autres solutions libres, comme Zimbra pour sa
messagerie ou encore Alfresco comme Gestion Électronique de Documents
(GED). Elle assure aussi des formations et des développements sur les
outils [[https://www.youtube.com/watch?v=cX53sSp4JQw&list=PL0Wd1JAi6QuHdwALwwJqj5TcfNYvjRbcs][QGIS]] ou encore PostGIS.

** Scenari : retour sur 20 ans de développements

/Un témoignage de Stéphane Crozat, co-concepteur de la suite logicielle [[http://scenari.org][Scenari]]./

La conception du logiciel Scenari commence en 1999 à l'Université de
Technologie de Compiègne. Une entreprise finance un projet de
recherche pour développer une base de fragments documentaires
réutilisables à assembler à la demande en fonction de contextes
d'usage. Ce premier projet permet une première réalisation qui va
trouver d'autres contextes de développement. Une équipe originale se
constitue, mi-labo, mi-entreprise, elle va atteindre une quinzaine de
personnes. D'autres écoles et universités se joignent à l'UTC pour
développer les usages de Scenari.

En 2004, Scenari est mis à disposition sous licence libre. La société
Kelis est créée pour accompagner son développement. Elle développe le
logiciel, professionnalise le service et diversifie ses usages. En
parallèle une communauté d'utilisateurs continue de bénéficier
gratuitement de Scenari et des évolutions reversées dans le logiciel.
En 2013 cette communauté se structure en association afin d'être force
de proposition et d'organiser la synergie entre les acteurs. En 2014,
Kelis devient une SCOP, elle compte aujourd'hui une quinzaine de
salariés.  En 2019 l'association Scenari embauche son premier salarié
et Kelis annonce la sortie de la version 5 de Scenari.

Aujourd'hui Scenari intègre fonctions accumulées par 20 années de
recherche, de développement et d'utilisation : édition structurée,
publication multisupports, gestion collaborative. Il est, peut-être
avant tout, un outil original par la logique de modélisation qui le
structure et qui permet d'adresser des chaînes éditoriales
diversifiées : supports pédagogiques, jeux sérieux, documentation
technique, publication audiovisuelle, édition juridique, etc.

=>>= Pour en savoir plus sur Scenari : [[http://scenari.org]]

** Prodige : un logiciel libre au coeur du SIG ATLASANTE

/Un témoignage de Xavier VITRY, coordinateur ATLASANTE, le SIG mutualisé des ARS et du Ministère de la Santé./

[[https://prodige.cerema.fr/][Prodige]] est une solution web qui permet de transformer des données
géographiques et non géographiques en ressources WEB, accessibles via
des services ou des API aux standards du WEB.  Prodige vous permet
ainsi de réaliser une plateforme pour constituer un patrimoine de
données cataloguées et sécurisées, et de maîtriser le partage de ces
données en produisant des services de visualisation ou de
téléchargement, mais aussi des représentations cartographiques
interactives, ou des graphiques de data viz, au bénéfice de
partenaires ou du grand public.

La gestion fine des droits d'accès permet d'ouvrir certaines
ressources pour une démarche de community sourcing ou de
crowdsourcing, y compris via des applications cartographiques sur
mobile.  Son architecture modulaire est motivée par l'attention portée
à sa capacité à évoluer et par son approche open source, lui
permettant de bénéficier des apports de la communauté active des
utilisateurs.

Prodige bénéficie d'une gouvernance partagée favorisant ainsi un
développement cohérent et consensuel de l'outil. Les instances
participatives (Comité de coordination, Comité de pilotage, Club
utilisateurs) sont des lieux d'échange et de partage qui permettent de
prendre en compte les besoins de chacun au bénéfice de la communauté.
Les membres représentent des services de l'Etat (écologie, santé), des
collectivités locales et des établissements publics (Cerema, ARS).

Concrètement, les financements apportés par les différents services
permettent d'élargir progressivement le périmètre fonctionnel des
modules Prodige. En novembre, c'est un nouveau visualiseur
cartographique adaptatif (responsive) qui fait son apparition.

=>>= Pour en savoir plus, voir [[https://prodige.cerema.fr/][le site de la communauté Prodige]].

** Collabora Online et LibreOffice à l'université de Lille

/Un témoignage de Pierre Boulet, Vice-président transformation numérique de l'université de Lille./

La DSI de l'Université de Lille a mis en production en septembre 2019
une suite bureautique collaborative permettant l'édition simultanée
par plusieurs utilisateurs de documents (textes, feuilles de calcul,
présentations) dans le navigateur web. Cette suite collaborative est
intégrée à la plateforme de partage de fichiers
[[https://nextcloud.univ-lille.fr][nextcloud.univ-lille.fr]].

Ainsi, un simple clic sur un document bureautique lance l'éditeur dans
la même fenêtre de navigateur et si le document est partagé, tous les
utilisateurs autorisés par ce partage peuvent le modifier
simultanément. Et comme les documents sont dans leur espace de
stockage sur nextcloud, ils restent éditables hors-ligne et
synchronisés automatiquement en local. Les cas d'utilisation sont
nombreux comme la prise de notes collaboratives en réunion, le travail
collaboratif en groupes pour des enseignements, la rédaction
d'articles de recherche en équipe, etc.

La solution logicielle retenue est [[https://www.collaboraoffice.com/collabora-online/][Collabora online]] qui repose sur 
[[https://www.libreoffice.org/][LibreOffice]] et est entièrement libre. Elle est la plus riche
fonctionnellement des solutions disponibles sur le marché et est
construite pour passer à l'échelle facilement. Les formats de
fichiers par défauts sont les formats [[https://fr.wikipedia.org/wiki/OpenDocument][OpenDocument]], seuls formats de
fichiers bureautiques standardisés et ouverts qui assurent
interopérabilité, portabilité et pérennité dans le temps et qui sont
les seuls formats recommandés dans le [[http://references.modernisation.gouv.fr/interoperabilite][référentiel général
d'interopérabilité]] ; mais les formats Microsoft sont aussi supportés.

=>>= Pour en savoir plus, lire la suitre de [[https://numerique.univ-lille.fr/accompagnement/suite-bureautique-collaborative][l'article sur le site de
l'université de Lille]].

* Retour sur les rencontres Geotrek 2019

Les troisièmes Rencontres Geotrek ont eu lieu les 7 et 8 novembre
dernier à Nîmes.

Confirmant le succès de cette application opensource de gestion et de
valorisation des sentiers, patrimoines et randonnées d'un territoire,
elles ont réuni plus de 130 participants, venus des 4 coins de la
France, agents de parcs naturels, départements, offices de tourisme,
et entreprises ont pu partager des expériences, découvrir les
nouveautés, prendre connaissance du groupement de commande et
participer à des ateliers techniques et thématiques.

La communauté d'utilisateurs et de concepteurs animée par le Parc
national des Ecrins, réunie autour d'un outil qu'ils développent
ensemble, démontre que la collaboration et le fonctionnement
participatif sont un puissant moyen d'action publique.

Le dynamisme des utilisateurs, des territoires et des partenaires
s'est illustré par un programme riche et intense avec des
présentations complémentaires courtes, illustrées et proposées par des
utilisateurs, témoins, entreprises, ou partenaires régionaux et
nationaux (APIDAE, IGN et la FFRandonnée).

Une belle occasion pour constater que la croissance des utilisateurs,
leur implication, et la continuité dans la gouvernance de la
communauté servent à alimenter la dynamique de développement de
Geotrek.

La communauté Geotrek atteint désormais une certaine maturité et de
plus en plus de structures trouvent leur place (et leur compte !) dans
ce modèle horizontal, collectif, transversal et qui réunit des
opérateurs issus de différents réseaux.

Pour en savoir plus, [[http://www.ecrins-parcnational.fr/actualite/geotrek-coulisses-portails-randonnee][lire l'article du Parc national des Ecrins sur
les rencontres Geotrek 2019]].

* Revue de presse

- Le programme DCANT de la DINUM était présent lors de la remise des prix [[https://territoire-numerique-libre.org/edition-2019/][Territoire Numérique Libre]].
- [[https://numerique.univ-lille.fr/accompagnement/suite-bureautique-collaborative][L'université de Lille utilise Collabora Online et LibreOffice]], à lire aussi [[https://www.arawa.fr/2019/11/23/arawa-annonce-le-deploiement-de-collabora-online-a-luniversite-de-lille/][ici]] et [[https://fr.blog.documentfoundation.org/2019/11/26/collabora-online-pour-plus-de-70-000-utilisateurs/][ici]].
- [[https://www.ccsd.cnrs.fr/2019/11/publication-du-code-de-hal-un-premier-pas-vers-lopen-source/][Publication du code de HAL : un premier pas vers l’open source]]
- [[https://linuxfr.org/news/anssi-emission-libre-a-vous-du-3-decembre-2019-podcasts-et-references][Entretien avec Guillaume Poupart, directeur général de l'Agence nationale de la sécurité des systèmes d’information dans l'émission « Libre à vous ! »]]
- [[https://www.nextinpact.com/news/108449-le-plan-cnrs-pour-atteindre-100-publications-en-libre-acces-idealement-dici-fin-2020.htm][Le plan du CNRS pour atteindre 100 % de publications en libre accès, « idéalement d'ici fin 2020 »]]
- [[https://www.lemondeinformatique.fr/actualites/lire-les-logiciels-libres-progressent-dans-les-collectivites-territoriales-77171.html][Les logiciels libres progressent dans les collectivités territoriales]]
- [[https://www.programmez.com/actualites/le-cnll-revele-la-difficulte-pour-les-clients-beneficier-de-lexpertise-des-editeurs-de-logiciels-29653][Le CNLL révèle la difficulté pour les clients à bénéficier de l'expertise des éditeurs de logiciels libres]]
- [[https://bef.cloud/2019/11/22/open-source-dans-le-deploiement-telecoms-pour-demain-grace-a-etalab/][L’Open Source dans le déploiement telecoms, pour demain grâce à Etalab ?]]
- [[https://open-source.developpez.com/actu/285485/Le-parti-d-Angela-Merkel-veut-que-les-logiciels-developpes-avec-l-argent-public-soient-accessibles-au-public-en-tant-que-logiciels-libres-et-apporte-son-soutien-a-une-initiative-de-la-FSFE/][Le parti d'Angela Merkel veut que les logiciels développés avec l'argent public soient accessibles au public]]
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/open-source-royal-navy][Royal Navy launched an open source toolkit for application development]]
- [[https://cryptonaute.fr/lunicef-lance-crypto-fonds-soutenir-technologies-open-source/][L'UNICEF lance un crypto-fonds pour financer des technologies open source]]
- [[https://www.nextinpact.com/news/108288-vincent-strubel-nous-parle-politique-open-source-anssi.htm][Vincent Strubel nous parle de la politique open source de l'ANSSI]]
- [[https://www.linkedin.com/pulse/coll%C3%A8ges-sib-ille-et-vilaine-cloud-s%C3%A9curit%C3%A9-byod-nouveaux-thomas][Collèges / SIB / Ille et Vilaine : cloud, sécurité, BYOD, nouveaux usages]]
- [[https://datanews.levif.be/ict/actualite/le-registre-national-tourne-desormais-sur-linux/article-news-1205079.html][Le Registre national belge tourne désormais sur Linux]]
- [[https://securite.developpez.com/actu/281305/Firefox-fait-un-sans-faute-lors-d-un-audit-realise-par-l-agence-allemande-de-securite-informatique-qui-le-recommande-comme-etant-le-navigateur-le-plus-securise/][Firefox fait un sans faute lors d'un audit réalisé par l'agence allemande de sécurité informatique]]
- [[https://www.toolinux.com/?Belgique-le-Registre-National-adopte-un-systeme-open-source][Belgique : le Registre National adopte un système open source]]
- [[https://www.silicon.fr/protection-des-donnees-lue-sinquiete-des-contrats-signes-avec-microsoft-par-ses-agences-265191.html][Protection des données : l'UE s'inquiète des contrats signés avec Microsoft par ses agences]]
- [[https://www.lemondeinformatique.fr/actualites/lire-pierre-baudracco-devient-co-president-du-cnll-76849.html][Pierre Baudracco devient co-président du CNLL]]
- [[https://www.gbif.org/fr/news/2mixX9oDrJI2W3AqPFOxI3/wherenext-gagne-le-defi-gbif-ebbe-nielsen-2019][GeoNature-atlas remporte un 3° prix au concours mondial des meilleurs outils opensource/opendata de biodiversité]]
- [[https://www.nextinpact.com/news/108156-le-ministere-linterieur-migre-sur-solution-libre-nextcloud.htm][Le ministère de l'Intérieur migre sur la solution libre Nextcloud]]
- [[https://speakerdeck.com/bluehats/point-sur-le-socle-interministeriel-de-logiciels-libres][Un point sur le Socle Interministériel des Logiciels Libres]], par Bastien Guerry.

** À l'international

- [[https://opengov.ellak.gr/2019/10/24/o-pigeos-kodikas-tou-logismikou-tis-gallikis-dimosias-diikisis-se-ena-apothetirio-anichtou-kodika/][Ο πηγαίος κώδικας του λογισμικού της Γαλλικής Δημόσιας Διοίκησης σε ένα αποθετήριο ανοιχτού κώδικα]] (« Les codes sources des logiciels de l'administration publique française dans un référentiel »)
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/tchap-messaging-service][Open Source Software powering the newly developed internal messaging service of the French government]] (« Un logiciel Open Source fait tourner le nouveau service de messagerie interne du gouvernement français »)
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/cooperative-interaction][Zürich Canton to share its software as open source]] (« Le canton de Zurich par ses logiciels en open source »)
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/etalab-open-source-repository][New platform listing the source codes of software used by French public administrations]] (« Une nouvelle plateforme pour lister les coodes sources de l'administration française »)
