#+title: Gazette #BlueHats n°11
#+date: 2021-06-23
#+author: DINUM
#+layout: post
#+draft: false
#+options: toc:nil num:nil H:4 ^:nil pri:t html-postamble:nil html-preamble:nil
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

#+begin_center
La gazette [[https://disic.github.io/gazette-bluehats/][#BlueHats]] est une lettre d'information bimestrielle sur le
logiciel libre dans, par et pour l'administration publique. Cette
gazette est la contribution de la [[https://www.numerique.gouv.fr/][DINUM]] au mouvement des #BlueHats,
les hackers d'intérêt général.

Vous pouvez vous y inscrire [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][depuis ce lien]], [[https://disic.github.io/gazette-bluehats/][lire les gazettes
précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]] pour les prochaines éditions.

Pour accéder à la version en ligne, [[https://disic.github.io/gazette-bluehats/gazette_bluehat_11/][cliquez ici]].  Bonne lecture !
-----
#+end_center

Ce mois-ci, la gazette BlueHats met l'accent sur les communs
numériques, avec un texte proposé par Wikimédia France et une nouvelle
rubrique « Le coin des communs ».  Le focus technique porte sur le
projet Open Terms Archive, que nous vous invitons à découvrir.  Nous
signalons quelques évolutions du Socle Interministériel de Logiciels
libres (SILL) et de code.etalab.gouv.fr.  Nous vous proposons enfin
notre revue de presse qui revient sur la circulaire sur la politique
publique de la donnée et la sortie du catalogue GouvTech.

Bonne lecture !

* Le mot de l'invitée : qu'est-ce qu'un commun numérique ?

/Un texte de Naphsica Papanicolaou, [[https://www.wikimedia.fr/][Wikimédia France]]./

Depuis quelques temps, le terme de « communs numériques » prend de
plus en plus d’importance dans le débat public.  Henri Verdier,
Ambassadeur pour le numérique, voit par exemple les communs numériques
comme les prémices d’une alternative aux grandes plateformes
numériques, devenues trop imposantes dans notre vie quotidienne (voir
[[https://portail-ie.fr/analysis/2937/les-communs-numeriques-solution-pour-une-autonomie-strategique-francaise-et-europeenne-durable][cet article]]).  Ils sont mis en avant aujourd’hui par une diversité
d'acteurs pour tenter de répondre au problème d’un internet toujours
plus monopolistique et privatisé.

Mais de quoi parle-t-on exactement ? Les communs sont des ressources
partagées, gérées et maintenues collectivement par une communauté qui
se donne des règles de gouvernance. Ils peuvent être naturels (une
forêt), matériels (une maison) ou immatériels (une informations).  Les
« communs numériques » désignent les ressources numériques gérées
comme des communs.  Toutes ces ressources sont « non-rivales » : les
partager avec A ne prive jamais B d’y accéder.  Toutes, en revanches,
ne sont pas libres, au sens qu’on donne usuellement à ce terme dans
l’univers numérique : les « communs numériques libres » sont ceux
partagés sous licence libre, comme les contenus des projets Wikimédia,
les contenus des bases de données d’OpenStreetMap ou d’OpenFoodFacts.

Quand on parle de communs, la question de la gouvernance est aussi
importante que celle de la ressource.  Elinor Ostrom, politologue et
économiste américaine, première femme a avoir reçu le prix Nobel
d'économie avec Olivier Williamson « pour son analyse de la
gouvernance économique, et en particulier, des biens communs », a
souligné que la préservation effective des communs par les communautés
qui en ont la charge est liée à la mise en place de modes de
gouvernance ouverte répondant à plusieurs critères. 

Bien que largement utilisés et reconnus par une grande partie de
l'écosytème numérique, les communs numériques sont, comme tous les
communs, fragiles. Ils continuent de se développer car il y a plus de
gens bien intentionnés que de personnes malveillantes. Mais cet
équilibre peut se rompre. Comme l’eau, la nature ou l’air, Wikipédia
est un commun fragile qui peut disparaître et dont il faut prendre
soin collectivement.

Pour préserver et valoriser les communs numériques libres, Wikimédia
France estime que chaque contributeur est important : c’est grâce à
chacun d’entre eux que sera portée la vision qui accompagne ces
projets et notamment leurs modèles de développement
collaboratif. C’est le pari fou de Wikipédia : faire confiance aux
gens en dotant les internautes d'un crayon afin qu'ils rédigent et
qu'ils participent à la plus grande encyclopédie au monde. Pour
protéger ces belles ressources issues de l’intelligence collective,
sachez que l'on compte sur vous autant que vous comptez sur Wikipédia.

* Le coin des communs

En juin, Wikimédia France et Etalab ont co-organisé un séminaire à
destination des agents culturels intitulé « Wiki, data et GLAM 2021 ».

Retrouvez [[https://www.wikimedia.fr/webinaire-wiki-data-glam-2021-etalab/][le programme]] et [[https://meta.wikimedia.org/wiki/Webinaire_wiki,_data_et_GLAM_2021/Documentation][les supports de présentation]] avec notamment
la [[https://speakerdeck.com/bluehats/presentation-de-la-licence-ouverte-2-dot-0][présentation par Etalab de la licence Ouverte 2.0]], qui rappelle que
les contenus publiés sous cette licence peuvent être librement
importés dans [[https://www.wikidata.org][www.wikidata.org]].

Le Labo Société Numérique revient sur [[https://labo.societenumerique.gouv.fr/2021/06/04/developpement-de-communs-numeriques-retours-dexperience-sur-3-projets-suivis-durant-nec-2020/][le développement de communs
numériques]] avec des retours d’expérience sur trois projets suivis
durant NEC 2020 et publie un point sur [[https://labo.societenumerique.gouv.fr/2021/04/26/strategie-communs-numerique-paris/][les communs numériques en
collectivité]], en se penchant sur la stratégie de la DSI de la Ville de
Paris.

En complément, vous pourrez lire une [[https://autrementautrement.com/2021/04/16/mettre-fin-au-desencastrement-entre-numerique-et-politique-publique/][interview de 
Pierre-Louis Rolle]], directeur du programme SoNum, qui revient sur
l'importance des communs numériques.

L'Institut Géographique National a lancé une [[https://www.ign.fr/participez-la-consultation-publique-sur-les-geo-communs][concertation publique de
l'IGN sur les géo-communs]].  La [[https://www.banquedesterritoires.fr/lign-consulte-sur-la-coproduction-de-donnees-geographiques][banque des territoires]] s'en est fait
l'écho, ainsi qu'[[https://www.acteurspublics.fr/articles/lign-amorce-son-virage-vers-les-communs-numeriques][acteurspublics.fr]].

* Focus : Open Terms Archive

/Une présentation de Clément Biron, développeur dans l'équipe de l'Ambassadeur pour le numérique. Clément a présenté le projet OTA lors d'un [[https://github.com/blue-hats/ateliers/blob/main/ateliers.org][atelier BlueHats]] que vous pouvez [[https://visio.incubateur.net/playback/presentation/2.0/playback.html?meetingId=9e1cec212d5b00a6edffdb255b00858adf5a647d-1620376802213][revoir ici]]./

Quel contrat ai-je accepté en utilisant un service numérique ? Les
conditions ont-elles changé depuis que j’utilise ces services ? Dans
quel sens évoluent-elles ? Sont-elles conformes aux discours de ces
acteurs et aux lois qui encadrent leurs pratiques ?

L'équipe de l'Ambassadeur pour le numérique a développé un outil
simple permet désormais de répondre à ces questions : [[https://opentermsarchive.org/fr][Open Terms
Archive]].

C'est un logiciel libre et collaboratif qui permet de suivre les
évolutions des conditions générales des principaux fournisseurs de
services en ligne en :

- enregistrant en temps réel chaque publication d'une nouvelle version des documents ;
- affichant spécifiquement les changements appliqués aux documents ;
- disposant d’un corpus documentaire de leur historique.

Open Terms Archive a vocation à s’enrichir et à devenir un Commun sur
lequel il sera possible de bâtir de nombreux usages : outils pour la
recherche en droit comparé, alertes ciblées, analyses linguistiques.
Les contributeurs sont les bienvenus, pour soumettre de nouveaux
services ou documents, améliorer le logiciel pour permettre une suivre
un plus grand nombre de langues et de juridiction ou suggérer des
modalités de valorisation des études de cas qui pourraient être
menées.

A titre de premier usage, nous avons ainsi développé [[https://disinfo.quaidorsay.fr/fr/open-terms-archive/scripta-manent?service=123Greetings&typeofdocument=Privacy+Policy][Scripta Manent]],
un premier outil très simple qui, pour 367 contrats, permet de mesurer
toutes les évolutions, ajouts ou suppressions, entre deux dates de
votre choix.

Développer des outils ouverts et collaboratifs, au service de la
transparence, s’inscrit dans deux des lignes de force de la diplomatie
numérique française :

- Incarner une souveraineté numérique européenne c’est-à-dire une réelle autonomie stratégique fondée sur une capacité d’action et de choix : il s’agit, à travers cet outil, de donner du pouvoir aux citoyens, entreprises et régulateurs pour décider librement de leurs pratiques et de leurs rapports vis-à-vis des acteurs numériques ;
- Construire un cadre de régulation du numérique fondé sur le dialogue multilatéral et multiacteurs : la création de biens communs à travers la formation d’alliances rassemblant tous les acteurs du numérique – Etats, société civile, acteurs privés – permet un dialogue continu et constructif autour des valeurs que nous souhaitons porter, et imposer, dans le monde numérique.

N’hésitez pas à nous contacter afin de :

- soumettre des services ou documents que vous souhaiteriez suivre. Pour rappel, vous pouvez également ajouter des documents en toute autonomie ;
- suggérer des modalités de valorisation des études de cas qui pourraient être menées ;
- poser toute question quant à l’utilisation de l’outil.

N’hésitez pas non plus à vous approprier cette ressource pour vos
propres projets, privés ou publics, y compris entrepreneuriaux.

* Le SILL et code.etalab.gouv.fr évoluent

Sur le SILL, deux nouveaux filtres sont apparus, l'un pour trouver les
solutions développées dans le cadre d'une mission de service public et
l'autre pour trouver les solutions faisant partie du marché de support
logiciels libres.  Un lien permet désormais de trouver une solution
dans le nouveau [[https://catalogue.numerique.gouv.fr/][catalogue GouvTech]], si elle y figure et vous pouvez
désormais [[https://www.mim-libre.fr/wp-content/uploads/2021/06/sill-2021.pdf][télécharger le SILL en PDF]].

Sur [[https://code.etalab.gouv.fr][code.etalab.gouv.fr]], vous pouvez réduire la liste des dépôts à
ceux qui sont hébergés dans une forge particulière et télécharger un
fichier =csv= ne contenant que les dépôts de la vue filtrée que vous
avez définie.

* Offres d'emploi

Pour renforcer ses équipes dédiées au logiciel libre, Etalab (DINUM)
recrute [[https://place-emploi-public.gouv.fr/offre-emploi/charge-e-de-mission-logiciels-libres-hf-reference-2021-635259/\]\]][un ou une chargé(e) ou de valorisation logiciels libres]].

Tchap a rejoint beta.gouv.fr et recrute [[https://beta.gouv.fr/recrutement/2021/06/15/charge.ou.chargee.de.deploiement.html][un ou une chargé(e) de
déploiement Tchap]].

Le Museum National d'Histoire Naturel galère encore à recruter [[https://www.patrinat.fr/sites/patrinat/files/atoms/files/2021/05/developpeur_web_python_projet_open-source_sur_la_biodiversite.pdf][un
développeur GeoNature (PostgreSQL-Python-Angular)]].

* Événements

Les 8 et 9 juin derniers se sont tenues les matinées de découverte
d'[[https://www.utilitr.org/conferences/decouverte-utilitr/][utilitR]], une communauté qui se forme autour du [[https://fr.wikipedia.org/wiki/R_(langage)][langage R]] et des
outils qui gravitent autour.

Le 25 juin prochain aura lieu la 2ème partie de l'atelier BlueHats sur
[[https://github.com/blue-hats/ateliers/blob/main/ateliers.org#25-juin--quelles-motivations-pour-contribuer-%C3%A0-des-projets-open-source--suite][les motivations pour contribuer à des projets open source]], présenté
par Nicolas Jullien.  Vous pouvez [[https://visio.incubateur.net/playback/presentation/2.0/playback.html?meetingId=9e1cec212d5b00a6edffdb255b00858adf5a647d-1617958857944][revoir la session précédente ici]].

Les 9 et 10 novembre prochain aura lieu le salon [[https://www.opensource-experience.com/][Open Source
Expérience]], un moment de rencontre important pour tout le secteur du
logiciel libre.

* Revue de presse

** Les suites de la circulaire sur la politique publique de la donnée

- [[https://www.numerique.gouv.fr/actualites/politique-donnee-algorithmes-et-codes-sources-une-circulaire-du-premier-ministre-renouvelle-ambition-francaise/][Politique de la donnée, des algorithmes et des codes sources : une circulaire du Premier ministre renouvelle l'ambition française]] (numerique.gouv.fr)
- [[https://www.acteurspublics.fr/articles/une-nouvelle-circulaire-relance-la-dynamique-douverture-des-donnees-et-codes-sources][Une nouvelle circulaire relance la dynamique d'ouverture des données et codes sources]] (acteurspublics.fr)
- [[https://www.cio-online.com/actualites/lire-une-circulaire-gouvernementale-precise-la-politique-publique-d-open-data-et-de-logiciel-libre-13154.html][Une circulaire gouvernementale précise la politique publique d'open data et de logiciel libre]] (cio-online.com)
- [[https://www.nextinpact.com/lebrief/46943/castex-signe-circulaire-pour-relancer-open-data-et-logiciels-libres][Castex signe une circulaire pour relancer l'open data et les logiciels libres]] (nextinpact.com)
- [[https://www.zdnet.fr/blogs/l-esprit-libre/circulaire-castex-creation-d-une-mission-logiciel-libre-et-communs-numeriques-a-la-dinum-39921871.htm][Circulaire Castex: création d'une mission logiciel libre et communs numériques à la DINUM]] (zdnet.fr)
- [[https://www.lemondeinformatique.fr/actualites/lire-le-gouvernement-etoffe-sa-politique-publique-d-open-data-et-logiciel-libre-82773.html][Le gouvernement étoffe sa politique publique d'open data et logiciel libre]] (lemondeinformatique.fr)
- [[https://www.lesechos.fr/tech-medias/hightech/la-france-a-la-relance-de-sa-politique-publique-de-la-donnee-1309868][La France à la relance de sa politique publique de la donnée]] (lesechos.fr)
  
** La DINUM lance le catalogue GouvTech

- [[https://www.numerique.gouv.fr/actualites/gouvtech-la-dinum-lance-un-catalogue-de-solutions-numeriques-utiles-aux-administrations/][GouvTech : la DINUM lance un catalogue de solutions numériques utiles aux administrations]] (numerique.gouv.fr)
- [[https://www.cio-online.com/actualites/lire-sabine-guillaume-cdm-label-dinum--la-phase-un-du-catalogue-gouvtech-est-a-but-pedagogique-13203.html][Sabine Guillaume (CdM Label, DINUM) : « la phase un du catalogue GouvTech est à but pédagogique »]] (cio-online.com)
- [[https://www.usinenouvelle.com/editorial/exclusif-l-etat-lance-un-catalogue-d-outils-numeriques-pour-le-service-public-a-partir-des-solutions-d-entreprises-francaises.N1093204][L'Etat lance un catalogue d'outils numériques pour le service public à partir des solutions d'entreprises françaises]] (usinenouvelle.com)
- [[https://www.archimag.com/demat-cloud/2021/05/18/la-dinum-partage-catalogue-gouvtech-en-faveur-administrations][La DINUM partage son catalogue GouvTech en faveur des administrations]] (archimag.com)
- [[https://www.lemondeinformatique.fr/actualites/lireamp-la-dinum-pousse-un-catalogue-d-applications-recommandees-82953.html][La Dinum pousse un catalogue d'applications recommandées]] (lemondeinformatique.fr)

** Du côté du secteur public français

- [[https://www.ouvrirlascience.fr/en-route-vers-louverture-des-codes-de-la-recherche/][Ouvrir la Science, en route vers l'ouverture des codes de la recherche]] (ouvrirlascience.fr)
- [[https://www.journaldunet.com/ebusiness/le-net/1502513-laure-lucchesi-etalab/]["Etalab doit contribuer à mettre à jour le logiciel de l'action publique"]] (journaldunet.com)
- [[https://www.recia.fr/2021/06/07/logiciels-libres-mutualisation-des-enjeux-forts-au-coeur-de-notre-groupement/][Recia.  Logiciels libres, mutualisation : des enjeux forts, au cœur de notre groupement]] (recia.fr)
- [[https://webinar.parsec.cloud/playback/presentation/2.0/playback.html?meetingId=100a6e6548ac7f217448041fbcc9a65efb5f32fd-1618400139812][Replay de l'événement Hub Open Source / secteur public du 14 avril]]
- [[https://www.numerama.com/tech/715233-pour-la-cnil-cest-clair-il-faut-lacher-les-google-docs-dans-lenseignement-superieur-et-la-recherche.html][Pour la Cnil, c'est clair : il faut lâcher les Google Docs dans l'enseignement supérieur et la recherche]] (numerama.com)
- [[https://www.cnil.fr/fr/la-cnil-appelle-evolutions-dans-utilisation-outils-collaboratifs-etatsuniens-enseignement-superieur-recherche][La CNIL appelle à des évolutions dans l'utilisation des outils collaboratifs étatsuniens pour l'enseignement supérieur et la recherche]] (cnil.fr)
- [[https://reseau.supdpo.fr/2021/05/21/tribune-suite-a-lavis-de-la-cnil-du-15-04-2021-relatif-aux-suites-collaboratives-for-education/][TRIBUNE -- Suite à la réponse de la CNIL du 15/04/2021 à la demande de conseil de la CPU et la CGE relative à l'utilisation des suites collaboratives "For Education"]] (supdpo.fr)
- [[https://www.lemondeinformatique.fr/actualites/lire-atos-gagne-le-marche-interministeriel-du-support-des-logiciels-libres-82578.html][Atos gagne le marché interministériel du support des logiciels libres]] (lemondeinformatique.fr)
- [[https://cnll.fr/news/atos-marche-interministeriel-support-logiciels-libres-avec-cnll/][Atos remporte le marché interministériel de support des logiciels libres en collaboration avec le CNLL]] (cnll.fr)
- [[https://itrnews.com/communiques-de-presse/45074/linagora-conforte-son-role-de-principal-fournisseur-de-letat-en-matiere-dexpertise-dans-le-domaine-des-logiciels-libres-pour-les-4-prochaines-annees][Linagora conforte son rôle de principal fournisseur de l'État en matière d'expertise dans le domaine des Logiciels Libres pour les 4 prochaines années]] (itrnews.com)
- [[https://www.lecese.fr/content/le-cese-a-adopte-lavis-pour-une-politique-de-souverainete-europeenne-du-numerique][Le CESE a adopté l'avis "Pour une politique de souveraineté européenne du numérique"]] (lecese.fr)
- [[https://www.silicon.fr/filiere-open-source-francaise-secteur-public-408916.html][La filière open source française en attend plus du secteur public]] (silicon.fr)
- [[https://www.lemonde.fr/education/article/2021/06/02/les-promesses-en-suspens-du-numerique-educatif_6082517_1473685.html][Les promesses en suspens du numérique éducatif]] (lemonde.fr)

** Du côté de la société civile

- [[https://cnll.fr/news/resultats-etude-filiere-open-source-france-2021/][Résultats de l'enquête sur l'état des lieux de la filière open source en France 2020/2021]] (cnll.fr)
- [[https://www.channelnews.fr/selon-le-conseil-national-du-logiciel-libre-letat-doit-mettre-en-oeuvre-une-veritable-politique-industrielle-en-faveur-de-la-filiere-103830][Selon le Conseil National du Logiciel Libre, l'Etat doit mettre en œuvre une véritable politique industrielle en faveur de la filière]] (channelnews.fr)
- [[https://classetice.fr/2020/12/21/sugarizer-la-premiere-plateforme-educative-pour-enfant/][Sugarizer, la première plateforme éducative pour enfant]] (classetice.fr)
- [[https://framablog.org/2021/05/25/oubliez-framaforms-le-logiciel-faites-de-la-place-a-yakforms/][Oubliez Framaforms-le-logiciel, faites de la place à Yakforms !]] (framablog.org)
- [[https://www.usine-digitale.fr/article/parasitisme-fondement-judiciaire-ideal-pour-sanctionner-l-utilisation-indue-d-un-logiciel-libre.N1089519][Parasitisme : fondement judiciaire idéal pour sanctionner l'utilisation indue d'un logiciel libre?]] (usine-digitale.fr)

** En Europe et au-delà

- L'Open Source Observatory publie les [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/guidelines-creating-sustainable-open-source-communities][guidelines for creating sustainable open source communities]].
- Dans le cadre de la conférence sur l'avenir de l'Europe, L'Union européenne consulte sur la [[https://futureu.europa.eu/processes/Digital][transformation numérique]].  Certaines propositions font écho au logiciel libre : [[https://futureu.europa.eu/processes/Digital/f/15/proposals/1791?locale=en][Tax incentives for companies to switch to open source]], [[https://futureu.europa.eu/processes/Digital/f/15/proposals/1364?locale=en][Universal income for open source maintainers]].
- [[https://blogs.eclipse.org/post/gael-blondelle/you-can-help-us-make-gaia-x-more-open][You can help us make GAIA-X more open]] (eclipse.org)
- [[https://ddg.fr/actualite/licences-saas-la-tension-monte-entre-editeurs-americains-de-licences-saas-et-clients-europeens/][Licences SaaS : la tension monte entre les éditeurs américains de licences SaaS et les clients européens]] (ddg.fr)
- [[https://joinup.ec.europa.eu/collection/better-legislation-smoother-implementation/news/april-virtual-breakfast-multidisciplinary-teams-key-takeaways][Key takeaways from the April virtual breakfast as part of the DigitAll conference]] (joinup.ec.europa.eu)
- [[https://www.youtube.com/watch?v=QgvossmO240&t=32s][DigitALL Public Conference 2021 | DAY 2 | The Role Of Open Source In The Public Sector]] (youtube.com)
- [[https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/][The White House - Executive Order on Improving the Nation's Cybersecurity]] (whitehouse.gov)
- [[https://www.lemondeinformatique.fr/actualites/lire-l-universite-du-minnesota-interdite-de-contribution-au-noyau-linux-82727.html][L'Université du Minnesota interdite de contribution au noyau Linux - Le Monde Informatique]] (lemondeinformatique.fr)
