#+title: Gazette #BlueHats n°6
#+date: <2020-07-16 jeu.>
#+author: DINUM
#+layout: post
#+draft: false

La gazette #BlueHats est une lettre d'information bimestrielle sur le logiciel libre dans, par et pour l'administration publique.  Cette gazette est la contribution de la [[https://www.numerique.gouv.fr/][DINUM]] au mouvement des #BlueHats, les hackers d'intérêt général.

Vous pouvez vous y inscrire [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][depuis ce lien]], [[https://disic.github.io/gazette-bluehats/][lire les gazettes précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]] pour les prochaines éditions.

* Focus sur Piaf: Pour des IA francophones

/Témoignage de Guillaume Lancrenon, travaillant avec Etalab sur PIAF./

** Quel est le besoin ?

Le recours à l’intelligence artificielle au sein de l’action publique est souvent identifié comme une opportunité pour interroger des textes documentaires et réaliser des outils de questions/réponses automatiques à destination des usagers. Interroger le code du travail en langage naturel, mettre à disposition un agent conversationnel pour un service donné, développer des moteurs de recherche performants, améliorer la gestion des connaissances, autant d’activités qui nécessitent de disposer de corpus de données d’entraînement de qualité afin de développer des algorithmes de questions/réponses. Aujourd’hui, il n’existe pas de jeu de données d’entraînement francophone ouvert qui permettrait d’entraîner et évaluer ces modèles.

** Quelle est notre ambition ?

C’est de construire un jeu de données francophones pour l’IA de manière ouverte et collaborative, pour amener une richesse syntaxique que le micro-travail (habituellement utilisé pour la création de ces jeux de données) ne permet pas d’obtenir. L’annotation d’articles étant une tâche importante dans l’IA, nous avons choisi d’en faire un projet participatif et pédagogique. Citoyens, associations, chercheurs et agents publics sont invités à y contribuer selon deux formats : des sessions d'annotation pour constituer la base de données d'évaluation, et une campagne grand public pour les données d'entraînement ! 

** Où en sommes-nous ?

Nous avons développé une plateforme d’annotation sous licence libre ([[https://piaf.etalab.studio][en ligne ici]]) basée sur un protocole scientifique inspiré du projet anglophone SQuAD, afin d’annoter des extraits d'articles de Wikipédia en français. Plus de 500 personnes ont aujourd’hui écrit des questions et des réponses sur notre plateforme, que nous avons ensuite publié sur data.gouv.fr de façon à ce que la recherche, les administrations, les citoyens etc… puissent les utiliser afin d’entrainer leurs modèles. 7500 questions, c’est la taille de notre jeu de données aujourd’hui. Nous avons besoin de vous pour continuer a le faire grandir, car notre objectif est d’atteindre les 25 000 à la fin de l’année. N’hésitez pas à contribuer !

De notre côté, nous commençons le développement de modèles pré-entraînés, et d’outils pré-conçus pour simplifier la recherche par « question-réponse » au sein de corpus de textes. Une collaboration avec l’outil open source Haystack de deepest.ai est envisagée. Toute aide sur le sujet sera la bienvenue !

* Retour sur l’Assemblée Générale 2020 de l’ADULLACT

L’Assemblée Générale de l’ADULLACT s’est tenue le jeudi 25 juin en visio-conférence (avec BigBlueButton), une première dans l’histoire de l’association. Plus de 70 participants étaient présents. En premier lieu, l’assemblée a voté la prolongation du mandat du CA de 1 an en raison du report des élections municipales. La prochaine AG se tiendra en présentiel à Montpellier, durant le Congrès ADULLACT qui été repoussé à juin 2021 en raison de la situation sanitaire.

L’Assemblée Générale a permis de faire le point sur tous les projets en cours, tels que l’édition 2020 du label Territoire Numérique Libre, la mise en service de l’application citoyenne DirectMairie, l’ajout d’une cartographie des métiers sur le Comptoir du Libre, et l’avancement du service demarches-simplifiees, en collaboration avec les développeurs de la DINUM.

Bastien Guerry (Etalab) était présent pour présenter la convention signée entre l’ADULLACT et la DINUM, et détailler ainsi les nouveaux axes de soutien : DCANT, SILL, catalogue LABEL, programme BETA, accessibilité, etc. Enfin, l’agglomération de Pau a présenté le projet IDQuart, un projet de participation citoyenne que Pau souhaite partager sous licence libre. Un Groupe de Travail Collaboratif va être lancé à la rentrée avec les collectivités intéressées. N’hésitez pas à vous faire connaître de l’ADULLACT pour plus d’informations.

=>>= Contact : [[mailto:contact@adullact.org][contact@adullact.org]]

* Obtenez ou renouvelez votre label « Territoire Numérique Libre »

Depuis 2016, l’association ADULLACT et ses partenaires organisent l’attribution du label Territoire Numérique Libre pour encourager et récompenser les initiatives en faveur des usages numériques libres et ouverts dans les collectivités territoriales. Le label comporte cinq niveaux, destinés à évaluer et accompagner les progrès des candidats. L'an dernier, un label de niveau 5 a été pour la première fois attribué à la ville de Nancy, récompensant ainsi la stratégie déployée en matière de logiciel libre et d'ouverture des données publiques. Les candidatures pour l’édition 2020 sont ouvertes jusqu’au 15 octobre à minuit. 

=>>= En savoir plus : https://territoire-numerique-libre.org/edition-2020/ 

=>>= Contact : [[mailto:label@territoire-numerique-libre.org][label@territoire-numerique-libre.org]]

* Le Comptoir du Libre présente sa cartographie des métiers

Le [[https://comptoir-du-libre.org][Comptoir du Libre]] est une plateforme de référencement des logiciels libres utiles aux missions de service public. Elle permet de découvrir de nouveaux logiciels libres, les collectivités utilisatrices et les prestataires proposant des services associés à ces solutions (formation, maintenance, etc.). La plateforme est interconnectée avec le catalogue en ligne du SILL. Désormais, elle dispose d'une cartographie des métiers pour faciliter les recherches sur le site. Cette cartographie a été co-construite avec des collectivités utilisatrices et a vocation a représenter le plus simplement possible les différents métiers représentés. Vous pouvez contribuer à cette cartographie en vous inscrivant pour déclarer et commenter les logiciels libres que vous utilisez.

=>>= En savoir plus :  https://comptoir-du-libre.org/fr/cartographie/

* Du nouveau dans le Socle Interministériel de Logiciels Libres

Depuis la parution du SILL 2020, de nouveaux logiciels ont été ajoutés au [[https://sill.etalab.gouv.fr/fr/software][Socle Interministériel de Logiciels Libres]] - voici la liste : Color Contrast Analyser, Démarches simplifiées, FusionDirectory, JOSM, Moodle, Open EDX, Pentaho CE, Esup-Pod, SPIP, Tracim, Xwiki, Pycharm CE, Chamilo.

=>>= Vous êtes agent public d'une administration et souhaitez être [[https://disic.github.io/sill/index.html][référent]] pour un logiciel libre que vous utilisez ?  [[https://sill.etalab.gouv.fr/fr/contact][Contactez-nous]] !

* De nouvelles ouvertures de codes sources

- La [[https://www.hatvp.fr/][Haute autorité pour la transparence de la vie publique]] ouvre son premier code source : https://gitlab.com/hatvp-open

- [[https://www.cerema.fr/fr/actualites/diffusion-open-source-chaine-traitement-images-satellites-du][Diffusion en Open Source de la chaine de traitement d'images satellites du Pôle Satellitaire du Cerema]]

- [[https://www.nextinpact.com/brief/etalab-propose-un-outil-open-source-de-pseudonymisation-12659.htm][Etalab propose un outil open source de pseudonymisation]]

- [[https://www.etalab.gouv.fr/][Etalab]] met à disposition une [[https://github.com/etalab/tchatcha][solution de captcha]]® pour le système de gestion de contenu TYPO3.

  Cette solution, écrite en Javascript et PHP, initialement développée par la société [[https://www.artifica.fr][Artifica]], met l'accent sur l'accessibilité.  Elle est librement adaptable à d'autres outils.

=>>= Vous pouvez suivre l'ajout de nouveaux codes sources en suivant [[https://code.etalab.gouv.fr/latest.xml][le flux RSS]] disponible depuis la plateforme [[https://code.etalab.gouv.fr][code.etalab.gouv.fr]].

* Des nouvelles de l'Europe

** Du côté de l'observatoire de l'open source de la Commission européenne

- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/sustainability-guidelines-webinar-takeaways][Ce qu'il faut retenir du wébinaire sur la soutenabilité des communautés open source (en)]]
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/document/integreat-case-studies-sustainability-public-sector-open-source-communities][Integreat: une étude de cas pour la soutenabilité des communautés open source du secteur public (en)]]
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/open-source-software-country-intelligence][Le point sur l'état de l'open source, pays par pays (en)]]

** Les eurodéputés votent un amendement en faveur du logiciel libre au Parlement

- [[https://www.developpez.com/actu/303461/Le-Parlement-europeen-recommande-que-soit-rendu-public-et-open-source-tout-logiciel-developpe-par-et-pour-les-institutions-de-l-UE/][Le Parlement européen recommande que soit rendu public et open source]]
- [[https://www.zdnet.fr/blogs/l-esprit-libre/les-eurodeputes-votent-un-amendement-en-faveur-du-logiciel-libre-au-parlement-39904477.htm#xtor=RSS-1][Les eurodéputés votent un amendement en faveur du logiciel libre au Parlement]]
- [[https://european-pirateparty.eu/european-parliament-strongly-recommends-any-software-developed-by-and-for-the-eu-institutions-to-be-made-publicly-available-under-free-and-open-source-software-licence/][European Parliament strongly recommends any software developed by and for the EU institutions to be made publicly available under Free and Open Source Software licence]]
- [[https://www.europarl.europa.eu/doceo/document/A-9-2020-0021_FR.html][Un rapport européen « reconnaît la valeur ajoutée que les logiciels libres et ouverts peuvent apporter au Parlement » (point 49)]]

* Revue de presse

** En France

- [[https://www.nextinpact.com/brief/eric-bothorel-investi-d-une-mission-sur---la-politique-de-la-donnee-et-des-codes-sources---12837.htm?skipua=1][Éric Bothorel investi d’une mission sur « la politique de la donnée et des codes sources »]] - voir [[https://www.legifrance.gouv.fr/affichTexte.do?cidTexte=JORFTEXT000042025804&categorieLien=id][le texte du décret]].
- [[https://www.lemonde.fr/pixels/article/2020/06/09/logiciels-libres-et-ecole-a-distance-la-sortie-de-la-suite-apps-education-precipitee-par-le-confinement_6042279_4408996.html][Logiciels libres et école à distance : la sortie de la suite « Apps.education » précipitée par le confinement]]
- [[https://www.lemondeinformatique.fr/actualites/lire-l-universite-de-nantes-s-appuient-sur-le-logiciel-libre-pour-deployer-ses-services-bureautiques-78839.html][L'Université de Nantes s'appuie sur le logiciel libre pour déployer ses services bureautiques]] - voir aussi le document présentant ce déploiement en détail, document présenté lors des [[https://www.jres.org/fr/accueil/][JRES 2019]].
- [[https://april.org/libre-a-vous-diffusee-mardi-5-mai-2020-sur-radio-cause-commune][Les logiciels libres dans l'Éducation nationale avec Luc Bourdot, responsable du Pôle national de compétences logiciels libres (émission Libre à vous ! sur la radio Cause commune)]]
- [[https://www.lecese.fr/content/le-cese-adopte-son-avis-services-publics-services-au-public-et-amenagement-des-territoires-lheure-du-numerique][Le CESE a adopté son avis "Services publics, services au public et aménagement des territoires à l'heure du numérique"]]
- [[https://linuxfr.org/news/audit-du-code-source-de-parcoursup-par-la-cour-des-comptes][Audit du code source de Parcoursup par la Cour des comptes]]
- [[https://www.acteurspublics.fr/evenement/education-une-boite-a-outils-numeriques-partages-a-lavenir-incertain][Éducation : une boîte à outils numériques partagés à l’avenir incertain]]
- [[https://www.zdnet.fr/blogs/l-esprit-libre/nouvelle-aquitaine-aquinetic-devient-naos-et-reagit-a-la-crise-du-covid-19-39905935.htm][Nouvelle-Aquitaine: Aquinetic devient Naos et réagit à la crise du Covid-19]]
- [[https://www.numerama.com/politique/625033-si-les-pages-wikipedia-de-deputes-sont-modifiees-depuis-le-parlement-ce-bot-les-expose.html][Si les pages Wikipedia de députés sont modifiées depuis l’Assemblée, ce bot les expose]]
- Le code de la dernière version MIMO de LibreOffice a enfin [[https://git.libreoffice.org/core/+/refs/heads/distro/mimo/mimo-6-2][été publié]] sur la branche Mimo de [[https://www.documentfoundation.org/][The Document Foundation]].
- [[https://www.ouvrirlascience.fr/dun-laboratoire-universitaire-a-40-millions-dutilisateurs-laventure-dun-logiciel-libre/][D’un laboratoire universitaire à 40 millions d’utilisateurs, l’aventure d’un logiciel libre]]

** Ailleurs

- [[https://www.developpez.com/actu/302807/Le-gouvernement-australien-publie-le-code-source-pour-Android-et-iOS-de-l-application-CovidSafe-qui-serait-moins-efficace-sur-les-iPhone/][Le gouvernement australien publie le code source pour Android et iOS de l'application CovidSafe]]
- [[https://www.toolinux.com/?Argent-public-code-public-la-ville-allemande-de-Munich-adhere][Argent public, code public : la ville allemande de Munich adhère]]
- [[https://open-source.developpez.com/actu/301505/Les-Pays-Bas-vont-ils-accorder-la-priorite-aux-logiciels-libres-dans-les-marches-publics-La-FSF-observe-et-entend-obtenir-que-les-softs-finances-par-le-contribuable-soient-libres/][Les Pays-Bas vont-ils accorder la priorité aux logiciels libres dans les marchés publics ? La FSF observe]]
- [[https://fsfe.org/news/2020/news-20200424-01.html][Netherlands commits to Free Software by default]]
- [[https://linuxfr.org/news/le-parlement-europeen-adopte-la-preference-pour-le-logiciel-libre-pour-les-institutions-de-l-ue][Le Parlement européen adopte la préférence pour le logiciel libre pour les institutions de l’UE]]
- [[https://cnll.fr/news/r%C3%A9ponse-du-cnll-%C3%A0-lappel-%C3%A0-contribution-de-france-strat%C3%A9gie-pour-un-apr%C3%A8s-soutenable/][Réponse du CNLL à l'appel à contribution de France Stratégie : Pour un "après" soutenable]]
- [[https://www.nextinpact.com/brief/le-controleur-europeen-des-donnees-tire-a-boulets-rouges-sur-les-contrats-entre-microsoft-et-les-institutions-europeennes-13034.htm][Le contrôleur européen des données tire à boulets rouges sur les contrats entre Microsoft et les institutions européennes]]
- [[https://www.lemondeinformatique.fr/actualites/lire-hambourg-evalue-une-migration-de-microsoft-a-l-open-source-79292.html][Hambourg évalue une migration de Microsoft à l'open source]]
- [[https://www.developpez.com/actu/305143/Immuni-l-application-italienne-de-suivi-des-contacts-est-developpee-en-open-source-sous-la-version-3-de-la-licence-GNU-Affero-General-Public/][Immuni, l'application italienne de suivi des contacts, est développée en open source]]
- [[https://www.linuxfoundation.org/blog/2020/04/a-guide-to-open-source-software-for-procurement-professionals/][A guide to open source software for procurement professionals]]
