#+title: Gazette #BlueHats n°1
#+date: 2019-06-10
#+author: DINUM
#+layout: post
#+draft: false

La gazette =#BlueHats= est une lettre d'information bimestrielle sur le
logiciel libre dans, par et pour l'administration publique.  Cette
gazette est la contribution de la DINSIC au mouvement des =#BlueHats=,
les hackers d'intérêt général.

Vous pouvez vous y inscrire [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][depuis ce lien]], [[https://disic.github.io/gazette-bluehats/][lire les gazettes
précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]] pour les prochaines éditions.

* Sharing & Reuse Awards 2019

Le [[https://ec.europa.eu/isa2/][programme ISA²]] est un programme de la Commission européenne pour
encourager l'intéropérabilité des solutions informatiques dans les
administrations publiques, les entreprises et les citoyens.

ISA² a publié une liste de [[https://ec.europa.eu/isa2/news/shortlisted-solutions-sharing-reuse-awards-2019-made-public_en][16 logiciels libres]] en lice pour remporter
le prix Share & Reuse 2019, parmi lesquels deux sont portés par le
secteur public en France : OpenFisca et Lutece.

Le prix sera remis le 11 juin 2019, lors de la conférence [[https://ec.europa.eu/isa2/events/sharing-reuse-conference-2019_en][Share &
Reuse 2019]], première conférence organisée par la Commssion européenne
sur le logiciel libre.

** OpenFisca

OpenFisca est une plate-forme open source portée par la [[https://www.numerique.gouv.fr/][DINSIC]] qui
permet de traduire la législation socio-fiscale en code informatique
afin de rendre la loi plus transparente et calculable.  OpenFisca
permet de concevoir des simulateurs à destination des usagers mais
aussi de simuler les conséquences budgétaires d’une réforme et son
impact redistributif sur la population.

- Pour en savoir plus : [[https://fr.openfisca.org/]]
- Code source : [[https://github.com/openfisca/]]

** Lutece

Lutece est un logiciel libre diffusé sous licence BSD par la mairie de
Paris depuis septembre 2002. Il a été accepté en 2014 au sein du
consortium Open Source international OW2.  Lutece était à l'origine un
Gestionnaire de contenu / Portail, mais a évolué au fil des années
vers un outil de développement d'applications Web. Il est très
largement utilisé par la mairie de Paris pour la réalisation de ses
sites, ses services numériques et ses applications métiers.

- Pour en savoir plus : [[https://fr.lutece.paris.fr/fr/]]
- Code source : [[https://github.com/lutece-platform]]

* Sortie du SILL 2019

Le Socle Interministériel des logiciels libres a été publié en mai
2019 par les groupes de mutualisation interministérielle (MIM) sur
leur site web, puis relayé par la DINSIC.

Co-construit par des communautés d’agents publics informaticiens de
l’État, des opérateurs et des collectivités territoriales, le socle
interministériel des logiciels libres est le catalogue de référence
des logiciels libres recommandés par l’État. 

Son périmètre - ne couvrant pas la totalité du système d’information
(SI) de l’État - classe les logiciels par thématiques : poste de
travail, gestion de parc, exploitation de serveurs et de bases de
données et environnements de développement. 

- Le SILL sur les groupes MIM : [[https://www.mim-libre.fr/]]
- Le lien vers la [[https://www.numerique.gouv.fr/actualites/decouvrez-le-socle-interministeriel-des-logiciels-libres-sill-2019/][brève de la DINSIC]]
- La [[https://disic.github.io/sill/index.html][version de travail du SILL]]

* Contributions à l'écosystème du logiciel libre

** La Cour des comptes contribue au logiciel libre Pubsweet

Afin de moderniser et fluidifier la rédaction de ses rapports, la Cour
des Comptes a décidé de lancer [[https://entrepreneur-interet-general.etalab.gouv.fr/defis/2019/plume.html][un projet]] dans le cadre du programme
Entrepreneur d'Interet General.  Trois personnes ont rejoint la Cour
des Comptes en janvier 2019 pour 10 mois.  Après avoir fait le point
des besoins de la Cour et un état des lieux des solutions existantes,
elles ont décidé de joindre leurs efforts à ceux de la [[https://coko.foundation/][Collaborative
Knowledge Foundation]] dans l'enrichissement de leur produit : [[https://coko.foundation/category/pubsweet/][Pubsweet]].

Entièrement libre, Pubsweet propose un ensemble de briques logicielles
avec lesquelles il est possible de créer simplement une plateforme de
publication sur mesure, incluant par exemple :

- le suivi des différents documents en cours de rédaction ;
- la gestion de leur état d'avancement (rédaction, relecture, correction...) ;
- la possibilité de décomposer un document en plusieurs sections modifiables indépendamment ;
- un éditeur simplifié séparant sémantique et mise en forme ;
- l'export vers des formats imprimables ou affichables directement
  dans le navigateur.

Rendez-vous dans quelques mois pour le bilan de cette collaboration !

** La DILA fait évoluer ses produits libres

La Direction de l'information légale et administrative ([[https://www.dila.premier-ministre.gouv.fr/][DILA]]) publie
des outils et ressources libres pour la qualité et l’accessibilité de
ses sites web. [[http://pidila.gitlab.io][PIDILA]] a publié une nouvelle version importante de
[[http://pidila.gitlab.io/scampi/][Scampi]] avec deux nouveaux modules (select, lien composite) et la
disparition de la dépendance à jQuery.  Scampi est lui-même disponible
en module npm.

Vous pouvez suivre et relayer [[https://twitter.com/pi_dila/status/1128292012648747009][l'annonce de ces évolutions sur Twitter]].

** « Codeurs en liberté » raconte une semaine de contribution au libre

« Codeurs en liberté » est une coopérative de développeurs
indépendants.  Ils ont récemment décidé de passer une semaine pour
contribuer à plusieurs à des logiciels libres commes framadate et
etherpad-lite.  Ces solutions étant répandues dans plusieurs
administrations, le récit de leur expérience pourra intéresser plus
d'un =#BlueHats= !

Lisez [[https://www.codeursenliberte.fr/entreprise/contribution_au_libre/][leur retour d'expérience]] sur leur site web.

* Sur l'accessibilité numérique

** Publication de modules sur l'accessibilité pour Firefox et Chrome

L’assistant RGAA (Référentiel Général d’Accessibilité pour les
Administrations) est une extension pour les navigateurs Chrome ou
Firefox.  Il permet aux personnes effectuant l’audit accessibilité
d’un site web de disposer d’une aide pratique à la mise en œuvre de
procédures de tests, critère par critère, comme par exemple la
désactivation de feuilles de styles, la mise en évidence des balises à
évaluer, etc.

La société empreinte digitale a mis à jour les modules de l'assistant
RGAA pour les navigateurs web [[https://addons.mozilla.org/fr/firefox/addon/assistant-rgaa/][Firefox]] et [[https://chrome.google.com/webstore/detail/assistant-rgaa/cgpmofepeeiaaljkcclfldhaalfpcand][Chrome]] en avril 2019 avec le
référentiel 3.2017 - les explications sont à lire sur [[https://blog.empreintedigitale.fr/2019/05/02/publication-de-lassistant-rgaa-avec-le-referentiel-3-2017/][leur blog]].

** Suites du Hackathon du Ministère de l'Intérieur autour de GLPI 

Les travaux du hackathon sur l'accessibilité du produit de Helpdesk
GLPI, organisé [[https://github.com/DISIC/gazette-bluehats/blob/master/gazette_bluehat_0.org#le-hackathon-glpi-du-minist%C3%A8re-de-lint%C3%A9rieur][en mars 2019]] par le Ministère de l'Intérieur, ont été
présentés ce 5 juin à la société TecLib, éditrice du projet.

Cette société a inscrit l'accessibilité numérique dans la feuille de
route de ses prochaines versions et des améliorations substantielles
devraient être apportées au produit.

TecLib présentera ses prochaines versions à notre groupe de travail
« accessibilité » avant leur publication et ce groupe pourra ainsi
l'accompagner dans l'amélioration de l'interface utilisateur pour les
personnes déficientes.

* Focus sur OCS Inventory NG

[[https://www.ocsinventory-ng.org/fr/][OCS Inventory NG]] est un logiciel de gestion de parc informatique avec
des fonctions d'inventaire et de télé-déploiement.  Ce logiciel est
utilisé par la Gendarmerie Nationale et la Police Nationale.

  La Gendarmerie Nationale a envisagé le déploiement de son 1er poste
  de travail sous OS libre en 2006.  Un inventaire des logiciels
  utilisés sur le parc informatique s’est alors avéré nécessaire pour
  évaluer la dépendance à Microsoft.  Malheureusement, aucune solution
  compatible avec GNU Linux et Windows n’était disponible sur le
  marché à l’époque.  Le projet OCS Inventory était certes naissant
  mais ne permettait pas de centraliser les tâches.  La communauté
  était en outre très réduite.  La Gendarmerie s’est donc lancée dans
  la refonte de cet outil avec pour objectif de l’adapter à son
  besoin.

  La communauté s'est alors élargie autour du développeur historique
  avec l’arrivée de 4 gendarmes contributeurs.  Une solution s’est
  rapidement dessinée et le logiciel OCS Inventory NG est né ! Il est
  capable de fournir une photographie précise de l’état d’un parc
  informatique avec des fonctions de télé-déploiement et une
  configuration centralisée.  Il permet ainsi des économies d’échelle
  (le parc de la Gendarmerie comprend, à titre d’exemple, environ 100
  000 machines) et des gains important de coût et de réactivité.
  L’ensemble des développements réalisés par des gendarmes ont été
  reversés à la communauté.

  OCS Inventory est désormais utilisé dans le monde entier par de
  nombreux grands comptes. La communauté historique a laissé sa place
  à une nouvelle formée autour de FactorFX, un industriel qui propose
  une offre de service dédiée.  La Gendarmerie entretient un lien
  régulier avec les nouveaux acteurs afin de leur faire bénéficier de
  son expérience dans le cadre des améliorations ou des corrections.

Merci à David Croizer et Arnaud Le Grignou pour ce « focus ».

* Candidatez pour le label « Territoire Numérique Libre 2019 »

Depuis 2016, l’association ADULLACT et ses partenaires organisent
l’attribution du label Territoire Numérique Libre pour encourager et
récompenser les initiatives en faveur du numérique libre et ouvert
dans les collectivités territoriales. Les candidatures pour l’édition
2019 sont ouvertes jusqu’au 15 octobre à minuit. L’annonce des
résultats et la remise des labels auront lieu durant le Salon des
maires qui se tiendra du 19 au 21 novembre à Paris.

- En savoir plus : [[https://territoire-numerique-libre.org/candidature-2019]]
- Contact : label@territoire-numerique-libre.org

* Appel à projets Latitudes

Latitudes est une association qui cherche à connecter les acteurs du
monde de l'intérêt général et ceux de l'innovation technologique en
mettant en oeuvre des projets sur lesquels s'engagent les membres de
la communauté de Latitudes, pour la plupart issus d'un réseau d'écoles
d'ingénieur.  Latitudes encourage la publication des réalisations en
logiciels libres et est notamment en lien avec le 110 bis, le lab
d'innovation de l'éducation nationale.

Latitudes a lancé un [[http://www.latitudes.cc/appel-a-projets][appel à projets]] auquel vous pouvez répondre
jusqu'au 20 juin.

* Evénements

** 12 et 13 juin : Conférence annuelle OW2

Avec pour thème cette année « Open Source : vers la maturité
industrielle » OW2con’19 propose deux journées de présentations et de
démonstrations de projets, de tables rondes, d’ateliers et d’orateurs
invités prestigieux.

Les discours inauguraux ont été confiés aux stratèges open source de
grandes entreprises comme Deutsche Telekom, Engineering, Ericsson,
IBM, Nokia, Orange et Siemens et d’organisations comme la DINSIC et la
Free Software Foundation Europe.  Le programme est rythmé par la
présentation des dernières améliorations de projets de la base de code
OW2 et permet d’aborder des sujets aussi divers que les tests, le
travail collaboratif, l’intelligence artificielle, l’IoT, le
multi-cloud, etc. Le thème de la gouvernance open source fait une
entrée marquée au programme cette année.

- Le [[https://www.ow2con.org/view/2019/Program?year=2019&event=OW2con19][programme]] de la conférence OW2con'19
- La page d'[[https://www.ow2con.org/view/2019/Register][inscription]]

** 13 et 14 juin : Printemps de l'Innovation Open Source

Le Printemps de l’Innovation Open Source (OSIS) est le rendez-vous de
l’excellence scientifique et technologique du libre et de l’open
source. L'OSIS réunit, sur plusieurs conférences thématiques,
chercheurs et ingénieurs des milieux académiques et industriels.

- 13 juin sur IOT & EMBARQUE CRITIQUE : le point sur les technologies
  permettant d'assurer la qualité des logiciels open source embarqués
  dans les équipements IoT.

- 14 juin sur le CLOUD : état de l'art et tendances futures des outils
  et frameworks open source utilisés dans l'écosystème Cloud, des
  stratégies d'orchestration aux architectures spécifiques.

Plus d'information sur [[http://open-source-innovation-spring.org/2019/][le site de l'événement]].

** Le 20 juin : Rencontre communautaire LemonLDAP::NG
 
LemonLDAP::NG est un logiciel d’authentification unique Web (Web‐SSO),
de contrôle d’accès et de fédération d’identité écrit en Perl.

- [[https://linuxfr.org/news/rencontre-communautaire-lemonldap-ng-le-20-juin-2019-a-strasbourg][L'annonce sur linuxfr.org]]
- La page du projet [[https://lemonldap-ng.org/welcome/][LemonLDAP-ng]]
- S'inscrire depuis [[https://framadate.org/rencontre-communautaire-llng-2019][cette page]]

** Du 19 au 22 juin : les journées PERL à Strasbourg

Acte 15 : trois langages, trois communautés, une hackfest, une
conférence.  Vous avez un projet écrit en (ou relatif à) perl, perl6
ou guile ?  L'envie d'apprendre ou d'utiliser l'un d'entre eux ?

Plus d'information sur le [[http://journeesperl.fr/jp2019/][site de l'événement]].

** 27 juin : Pour une charte de la « ville intelligente »

Dédié aux décideurs territoriaux, cet journée doit permettre d'engager
une vraie réflexion autour des outils et bonnes pratiques de la ville
intelligente, et notamment sur l’usage de logiciels libres.  Avec pour
objectif principal la co-rédaction de 10 préconisations en faveur
d’une ville intelligente, éthique et responsable.  La charte qui en
découlera sera signée lors du prochain Sommet International de
l’Innovation en Villes Médianes (SIIViM).

- Date et lieu : jeudi 27 juin 2019 à Bordeaux
- [[https://adullact.org/agenda/72-groupe-de-reflexion-charte-de-la-smart-city?date=2019-06-27-14-00][Inscriptions]] sur le site de l'Adullact.

** Cet automne : le Hackathon Data Secours

À l'automne 2019, le Ministère de l'Intérieur organise un *Hackathon
Data Secours* autour des services de secours d'urgence, en partenariat
avec au Atraksis, Etalab, la Fédération Nationale des
Sapeurs-Pompiers, le SDIS 77 et le SDIS 91.

Ce hackathon portera sur l'ouverture et la valorisation de données
pour des services de secours d'urgence aux personnes.  Il s'adresse
aux data scientists, pompiers, développeurs, personnels du SAMU,
étudiants ou citoyens.

- [[https://www.eventbrite.fr/e/billets-hackathon-data-secours-62314011887][Inscription]]
- Contact : hackathon-secours@interieur.gouv.fr
- Suivre sur Twitter : #hackathondatasecours

* Revue de presse

- lemondeinformatique.fr : [[https://www.lemondeinformatique.fr/actualites/lire-les-impacts-positifs-de-la-politique-open-source-en-france-75160.html][Les impacts positifs de la politique open source en France]]
- lagazettedescommunes.com : [[https://www.lagazettedescommunes.com/620191/lopen-data-ne-peut-pas-se-passer-du-logiciel-libre/][L’open-data ne peut pas se passer du logiciel libre]]
- liberation.fr : [[https://www.liberation.fr/debats/2019/06/04/logiciel-libre-il-faut-mettre-la-technologie-au-service-des-villes-et-des-citoyens_1731392][Logiciel libre : il faut mettre la technologie au service des villes et des citoyens]]
- ANSSI : [[https://www.ssi.gouv.fr/actualite/la-securite-des-objets-connectes-cest-possible-avec-le-logiciel-libre-la-preuve-avec-le-projet-wookey/][La sécurité des objets connectés, c’est possible avec le logiciel libre ! La preuve avec le projet WooKey]]
- NextImpact : [[https://www.nextinpact.com/news/107840-justice-marche-public-ne-peut-favoriser-solution-proprietaire.htm][Justice : un marché public ne peut favoriser un logiciel propriétaire]]
- developpez.com : [[https://www.developpez.com/actu/259501/France-quels-sont-les-logiciels-libres-que-l-Etat-recommande-en-2019-La-liste-des-logiciels-conseilles-est-disponible-a-travers-le-SILL-2019/][France : quels sont les logiciels libres que l'État recommande en 2019 ?]]
- cio-online.com : [[https://www.cio-online.com/actualites/lire-sill-2019-le-referentiel-de-logiciels-libres-de-l-etat-actualise-11192.html][SILL 2019 : le référentiel de logiciels libres de l'Etat actualisé]]
- cigref.fr : [[https://www.cigref.fr/sill-2019-mise-a-jour-referentiel-logiciels-libres-dinsic-dsi-etat][#SILL2019 : mise à jour du référentiel de logiciels libres de la DINSIC, la DSI de l’Etat]]
- numerama.com : [[https://www.numerama.com/tech/510361-quels-sont-les-logiciels-libres-que-letat-conseille-en-2019.html][Quels sont les logiciels libres que l’État conseille en 2019 ?]]
- lemondeinformatique.fr : [[https://www.lemondeinformatique.fr/actualites/lire-la-dinsic-actualise-son-referentiel-de-logiciels-libres-75165.html][La Dinsic actualise son référentiel de logiciels libres]]
- april.org : [[https://april.org/l-usage-des-logiciels-libres-un-des-criteres-d-obtention-du-label-numerique-inclusif][L'usage des logiciels libres un des critères d'obtention du label « numérique inclusif »]]
- lemondeinformatique.fr : [[https://www.lemondeinformatique.fr/actualites/lire-pour-une-vision-eco-responsable-de-la-conception-web-75179.html][Pour une vision éco-responsable de la conception web]]
- linuxfr.org : [[https://linuxfr.org/news/interview-de-bastien-guerry-referent-logiciels-libres-a-la-dinsic][Interview de Bastien Guerry, référent logiciels libres à la DINSIC]]

* Une suggestion ?

Faites-nous en part en répondant tout simplement à ce message, en écrivant à [[mailto:bluehats@etalab.gouv.fr][bluehats@etalab.gouv.fr]] ou en [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][ouvrant un ticket]].

Merci d'avance pour vos contributions !

* Désincription

Pour vous désinscrire de la gazette =#BlueHats=, c'est [[https://infolettres.etalab.gouv.fr/unsubscribe/bluehats@mail.etalab.studio][par ici]].

