#+title: Gazette #BlueHats n°10
#+date: 2021-04-11
#+author: DINUM
#+layout: post
#+draft: false
#+options: toc:nil num:nil H:4 ^:nil pri:t html-postamble:nil html-preamble:nil
#+html_head: <link rel="stylesheet" type="text/css" href="style.css" />

#+begin_center
La gazette [[https://disic.github.io/gazette-bluehats/][#BlueHats]] est une lettre d'information bimestrielle sur le
logiciel libre dans, par et pour l'administration publique. Cette
gazette est la contribution de la [[https://www.numerique.gouv.fr/][DINUM]] au mouvement des #BlueHats,
les hackers d'intérêt général.

Vous pouvez vous y inscrire [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][depuis ce lien]], [[https://disic.github.io/gazette-bluehats/][lire les gazettes
précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]] pour les prochaines éditions.

Pour accéder à la version en ligne, [[https://disic.github.io/gazette-bluehats/gazette_bluehat_10/][cliquez ici]].  Bonne lecture !
-----
#+end_center

* Focus : Vive le numérique libre

Introduit par M. Eric Bothorel, député et responsable d’une mission
relative à la politique publique de la donnée dont le rapport a été
remis au Premier ministre le 23 décembre 2020, le millésime 2021 de la
[[http://www.amue.fr/systeme-dinformation/metier/la-collection-numerique/][collection numérique]] publiée par l'AMUE présente le Libre sous toutes
ses formes.

Débats d’idées, retours d’expériences ou interviews, la thématique est
abordée dans ses nombreuses dimensions et toute sa richesse. C’est un
beau panorama de la question du Libre que nous vous partageons avec
plaisir. Ce numéro ne manquera pas de nourrir vos réflexions. Que ses
nombreux contributeurs en soient chaleureusement remerciés !

=>>= Accéder au numéro : http://amue.fr/presentation/articles/article/la-collection-numerique-parlons-libre/

* Rencontres Open Source & acteurs publics mardi 13 avril

Le [[systematic-paris-region.org][Pôle Systematic]] propose aux acteurs publics de rencontrer des
offreurs de solutions Open Source sélectionnés pouvant répondre à
leurs besoins IT lors de rendez-vous express en one-to-one ciblés 
et programmés.

=>>= Mardi 13 avril après-midi, 100% visio
=>>= Inscriptions : https://server.matchmaking-studio.com/fr/RendezVousOneToOneOpenSource/  
=>>= Lien pdf : https://systematic-paris-region.org/wp-content/uploads/2021/03/RDV121_Acteurspublics.pdf  

* Publication de l'annuaire du CNLL en bêta

La nouvelle version de l'annuaire des entreprises du libre du CNLL
inclut de nombreuses améliorations et ajouts de fonctionnalités.  Ces
progrès permettent au [[https://cnll.fr/][CNLL]] de mettre à disposition des utilisateurs de
solutions open source un annuaire complet et thématique, offrant un
large choix de critères de recherche :

- par nom d'entreprise ;
- par localisation (région, ville, cluster) ;
- par solutions et technologies ;
- par métier (éditeur, société de services, hébergeur).

L'annuaire inclut également une visualisation cartographique de la
localisation des entreprises.  Présentée via une interface conviviale,
intuitive et ergonomique, cet outil se veut être compréhensible en
quelques minutes par l'utilisateur et répondre à son besoin. Nous
sommes impatients de recevoir des retours d'expérience utilisateurs et
suggestions possibles d'améliorations.

=>>= L'annuaire : https://annuaire.cnll.fr

=>>= L'annonce : https://cnll.fr/news/annuaire-des-entreprises-du-cnll-nouvelle-version/

* De-ci de-là

- [[https://visio.incubateur.net/b/bas-vwv-2ww][Les vidéos des sessions des ateliers BlueHats sont publiques]]
- [[https://danescenari.edu.ac-lyon.fr/sc/pub/Visios_BBB_web/co/module_Visios_BBB.html][Présentation de la solution de visioconférence de l'Éducation Nationale]]
- [[https://twitter.com/jbuget/status/1366128542241730572][Le moteur open source de pix.fr réutilisé pour ecriplus.fr]]

* Revue de presse

- [[https://www.journaldunet.com/solutions/dsi/1498485-jitsi-meet-vs-nextcloud-talk-le-match-des-zoom-open-source/][Match des Zoom open source : Jitsi, la simplicité, vs Nextcloud Talk, l'efficacité]] (journaldunet.com, 8 mars 2021)
- [[https://www.banquedesterritoires.fr/geotrek-du-logiciel-libre-la-creation-dun-ecosysteme-numerique-de-la-randonnee][Geotrek : du logiciel libre à la création d’un écosystème numérique de la randonnée]] (banquedesterritoires.fr, 26 février 2021)
- [[https://adullact.org/breves/68-actualite/vie-associative/958-le-nouveau-service-demarches-simplifiees-est-operationnel][Le nouveau service Démarches Simplifiées de l'Adullact est opérationnel]] (adullact.org, 25 février 2021)
- [[https://www.franceculture.fr/emissions/la-question-du-jour/pourquoi-les-logiciels-libres-interessent-ils-les-etats][Pourquoi les logiciels libres intéressent-ils les États ?]]  (franculture.fr, 16 février 2021)
- [[https://www.ouvrirlascience.fr/wp-content/uploads/2021/02/Comments-by-France-on-UNESCO-first-draft-reco-Open-Science.pdf][Le retour de la France sur le premier draft des recommendations UNESCO sur la science ouverte]] (ouvrirlascience.fr, Décembre 2020)
