#+title: Gazette #BlueHats n°5
#+date: 2020-04-24
#+author: DINUM
#+layout: post
#+draft: true

La gazette #BlueHats est une lettre d'information bimestrielle sur le logiciel libre dans, par et pour l'administration publique.  Cette gazette est la contribution de la [[https://www.numerique.gouv.fr/][DINUM]] au mouvement des #BlueHats, les hackers d'intérêt général.

Vous pouvez vous y inscrire [[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio][depuis ce lien]], [[https://disic.github.io/gazette-bluehats/][lire les gazettes précédentes]] et [[https://github.com/DISIC/gazette-bluehats/issues/new/choose][proposer des contenus]] pour les prochaines éditions.

* Publication du SILL 2020

Le socle interministériel des logiciels libres (SILL) 2020 est publié.  Ce catalogue de référence des logiciels libres recommandés par l’État est le fruit d’une collaboration entre une communauté d’agents publics informaticiens et la direction interministérielle du numérique.

Jusqu'en 2019, le SILL était mis à jour une fois par an et publié sous forme de document PDF.  Il est désormais mis à jour /en continu/ et publié par [[https://www.etalab.gouv.fr/][Etalab]] sous forme de site web: [[https://sill.etalab.gouv.fr]].

Cette interface permet de faire une recherche rapide, d'avoir des URLs stables pour chaque logiciel, de filtrer par catégorie de logiciel ou par statut (« recommandé » ou « en observation »), de voir [[https://sill.etalab.gouv.fr/fr/stats][quelques chiffres]] utiles, de vous abonner au [[https://sill.etalab.gouv.fr/updates.xml][fil RSS des mises à jour]] et de consulter les catalogues de deux années passées.  À noter que l'interface est aussi accessible en [[https://sill.etalab.gouv.fr/it/software][italien]], [[https://sill.etalab.gouv.fr/de/software][allemand]], [[https://sill.etalab.gouv.fr/es/software][espagnol]] et [[https://sill.etalab.gouv.fr/en/software][anglais]].

Du côté des nouveaux logiciels référencés, nous trouvons entre autres la solution de visioconférence [[https://sill.etalab.gouv.fr/en/software?id=196][BigBlueButton]], le logiciel d'hébergement décentralisé de vidéos [[https://sill.etalab.gouv.fr/en/software?id=197][Peertube]], des logiciels produits par le secteur public comme [[https://sill.etalab.gouv.fr/en/software?id=194][VITAM]], [[https://sill.etalab.gouv.fr/en/software?id=185][Archifiltre]], [[https://sill.etalab.gouv.fr/fr/software?id=200][Openfisca]] ou le [[https://sill.etalab.gouv.fr/fr/software?id=201][SDK Géoportail]], ainsi que d'autres logiciels importants comme [[https://sill.etalab.gouv.fr/fr/software?id=195][Opale]], [[https://sill.etalab.gouv.fr/fr/software?id=202][Zimbra]], [[https://sill.etalab.gouv.fr/en/software?id=184][Redis]], [[https://sill.etalab.gouv.fr/en/software?id=193][OpenShot]] ou [[https://sill.etalab.gouv.fr/en/software?id=182][RStudio]].

En tout, ce sont *190 logiciels libres référencés*, soit *34 de plus* qu'en 2019.  Parmi les logiciels du SILL 2020, 144 ont le statut « recommandés » et 46 sont marqués « en observation ».

Enfin, la communauté des référents SILL s'est élargie : si vous êtes agent public de fonction publique d'État ou hospitalière et que vous souhaitez contribuer au référencement d'un logiciel libre, les groupes MIM qui font le SILL sont là pour vous accueillir !  Vous pouvez pour cela écrire à =opensource@data.gouv.fr=

=>>= Pour consulter le SILL, rendez-vous sur [[https://sill.etalab.gouv.fr]].

* Focus sur le logiciel libre à la DANE de Lyon

/Un témoignage de Cédric Frayssinet, chargé de Missions DANE, référent Usages & Outils./

La Délégation Académique au Numérique Éducatif (DANE) est un service du [[http://dane.ac-lyon.fr][Rectorat de Lyon]]. Il est piloté par un DAN, 2 DAN adjoints et composé d’une grosse dizaine d’enseignants en mi-temps. Ce fonctionnement permet une meilleure prise en compte des usages du numérique dans les établissements scolaires.

Depuis toujours, la DANE de Lyon s’est positionnée en faveur des logiciels libres.  Outre l’aspect éthique qui concerne encore trop peu de monde, ce sont les seuls logiciels que tous les élèves peuvent installer et utiliser chez eux, sans contraintes et en respectant les enjeux de la protection des données personnelles.

Il y a quelques années, la solution [[https://pcll.ac-dijon.fr/eole/][Eole-Scribe]] a été installée dans tous les collèges et lycées de l’académie, avec un cahier des charges d’installation d’applications basés quasi exclusivement sur des logiciels libres : LibreOffice, VLC, Mozilla Firefox, Audacity, OpenShot, Geogebra, etc.

Aujourd’hui, nous développons au maximum les services aux usagers basés sur les logiciels libres. Outre les blogs WordPress, les sites SPIP, nous avons été la première académie à déployer [[https://tube.ac-lyon.fr][une instance PeerTube]] pour offrir à nos enseignants une solution de diffusion vidéos, libre, éthique et très performante !

Cette solution, développée par l'association d'éducation populaire [[https://framasoft.org/fr/][Framasoft]], a été déployée facilement par la DSI via Docker et la barre des 100000 vues a été passée récemment.  Outre les aspects déjà mentionnés ci-dessus, nous apprécions les mises à jours aisées et l’implémentation du protocole BitTorrent pour regarder une vidéo, ce qui allège considérablement la bande passante fournie par le Rectorat.  Nous n’utilisons pas encore la fédération d’instances mais cela devrait ouvrir de nouveaux usages à moyen terme.

Pour finir, nous venons d’ouvrir un cloud avec NextCloud pour tous nos enseignants du 1er degré afin de les aider dans le partage des fichiers à destination des élèves.  Ce service était beaucoup attendu et nous ne doutons pas qu’il saura séduire les professeurs des écoles !

=>>= Pour en savoir plus sur la DANE de Lyon : https://dane.ac-lyon.fr

* Et si vous organisiez le prochain événement #BlueHats ?

Tout l'écosystème du logiciel libre est invité à organiser des événements #BlueHats.

Que vous soyez une administration, une association ou une entreprise, si vous organisez des ateliers autour de logiciels libres utilisés dans l'administration, vous pouvez librement vous emparer du hashtag #BlueHats et organiser des événements avec des chapeaux bleus !

L'équipe d'[[https://www.etalab.gouv.fr/accompagnement-logiciels-libres][Etalab]] est à votre disposition pour aider si besoin.

* Retour sur les événements #BlueHats passés

** 1er sprint open source de l'administration

La direction interministérielle du numérique (DINUM) et le 110 bis, le lab d’innovation de l’Éducation nationale, ont rassemblé la communauté BlueHats pour le premier sprint open source du secteur public les 19 et 20 novembre derniers.

=>>= Lire la suite sur le [[https://www.education.gouv.fr/retour-sur-le-premier-sprint-open-source-bluehats-de-l-administration-89270][site du l'éducation nationale]] ou le [[https://www.numerique.gouv.fr/actualites/retour-sur-le-premier-sprint-open-source-bluehats-administration/a][site de la DINUM]]

** La journée #BlueHats au Paris Open Source Summit 2019

Un an après le lancement de 2018, même lieu, même événement, même ferveur : les #BlueHats – les hackers d’intérêt général – se sont réunis en décembre dernier pour une nouvelle journée de rencontres et d’échanges dans le cadre du Paris Open Source Summit, qui l’avait vu naître un an auparavant sous l’impulsion de la DINUM (alors DINSIC).

Salle comble tout au long de la journée : il en fallait bien plus qu’une grève de transports pour décourager les passionnés d’open source dans l’administration ! Les 22 intervenants ont présenté la façon dont ils développent ou utilisent des solutions libres dans leurs administrations.

=>>= Retrouvez l’ensemble des supports de présentation [[https://forum.etalab.gouv.fr/t/journee-bluehats-lors-du-paris-open-source-summit-le-11-decembre-2019/4614][sur le forum d'Etalab]]

* Publication du programme européen Open Source Observatory

Le programme européen Open Source Observatory (OSOR) a publié [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/document/french-government-launches-house-developed-messaging-service-tchap][une étude de cas sur Tchap]] ainsi que des rapports sur l'[[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/open-source-software-country-intelligence#France][état de l'open source]] dans le secteur public européen.

=>>= Pour suivre les informations d'OSOR: https://twitter.com/OSOReu

* Revue de presse

- [[https://blog.scaleway.com/2020/scaleway-multiplie-les-solutions-cloud-pour-soutenir-la-continuite-des-services-de-letat-dans-la-crise-du-covid-19/][Scaleway multiplie les solutions cloud pour soutenir la continuité des services de l’État dans la crise du COVID-19]] (Scaleway, 2 avril 2020)
- [[https://home.cern/news/news/knowledge-sharing/cern-updates-its-open-hardware-licence][CERN updates its Open Hardware Licence]] (CERN, 12 mars 2020)
- [[https://www.zdnet.fr/blogs/l-esprit-libre/la-commission-europeenne-recommande-a-ses-employes-de-passer-a-signal-39899925.htm][La Commission européenne recommande à ses employés de passer à Signal]] (ZDNET, 29 février 2020)
- [[https://www.zdnet.fr/blogs/l-esprit-libre/les-gendarmes-et-la-justice-utilisateurs-du-logiciel-libre-vlc-39899783.htm][Les gendarmes et la justice, utilisateurs du logiciel libre VLC]] (ZDNET, 26 février 2020)
- [[https://www.numerama.com/tech/607720-la-commission-europeenne-adopte-signal-sauf-pour-les-discussions-tres-sensibles.html][La Commission européenne adopte Signal, sauf pour les discussions très sensibles]] (Numerama, 25 février 2020)
- [[https://www.lemondeinformatique.fr/actualites/lire-l-universite-de-lille-mise-sur-le-collaboratif-open-source-pour-la-mobilite-78081.html][L'Université de Lille mise sur le collaboratif open source pour la mobilité]] (lemondeinformatique.fr, 16 février 2020)
- [[https://www.candidats.fr/post/2020/02/11/municipales-2020-liste-des-signataires-du-pacte-du-logiciel-libre][Municipales 2020 - Liste des signataires du Pacte du Logiciel Libre]] (candidats.fr, 11 février 2020)
- [[https://www.lemondeinformatique.fr/actualites/lire-avec-la-fin-de-windows-7-la-coree-du-sud-va-migrer-sur-linux-78029.html][Avec la fin du support de Windows 7, le gouvernement sud-coréen a élaboré une stratégie pour migrer à grande échelle sur un OS Linux]] (lemondeinformatique.fr, 7 février 2020)
- [[https://www.microlinux.fr/lycee-sous-linux/][Un lycée 100 % sous Linux… ou presque]] (microlinux.fr, 30 janvier 2020)
- [[https://linuxfr.org/news/sambaedu-4-une-solution-de-serveurs-pedagogiques-libres-bases-sur-gnu-linux][SambaÉdu 4, une solution de serveurs pédagogiques libres basés sur GNU/Linux]] (linuxfr.org, 5 janvier 2020)
- [[https://www.ladepeche.fr/2019/12/23/boe-decroche-le-label-territoire-numerique-libre,8622489.php][Boé décroche le Label "Territoire Numérique Libre"]] (ladepeche.fr, 23 décembre 2019)
- [[https://joinup.ec.europa.eu/collection/open-source-observatory-osor/news/french-labour-code-open-source][France to launch the Digital Labour Code open source platform]] (joinup.ec.europa.eu, 20 décembre 2020)
- [[http://www.courrierdesmaires.fr/84800/ladullact-pour-des-logiciels-libres-au-sein-de-la-collectivite/][Travailler avec l’Adullact, pour des logiciels libres au sein de la collectivité]] (courrierdesmaires.fr, 13 décembre 2019)
- [[https://inno3.fr/actualite/conjuguer-open-source-et-science-ouverte-opportunites-et-leviers-daction][Conjuguer open source et science ouverte : opportunités et leviers d’action]] (inno3, 11 décembre 2019)
- [[https://www.channelnews.fr/la-france-leader-de-lopen-source-en-europe-93508][La France leader de l’open source en Europe]] (channelnews.fr, 11 décembre 2019)
- [[https://www.ouvrirlascience.fr/note-dopportunite-sur-la-valorisation-des-logiciels-issus-de-la-recherche/][Note d’opportunité sur la valorisation des logiciels issus de la recherche]] (www.ouvrirlascience.fr, novembre 2019)
- [[https://www.lebigdata.fr/cloud-aws-drogue-douce][Le Cloud AWS est une drogue douce dangereuse selon le ministère de l’Economie]] (www.lebigdata.fr, 15 octobre 2019)
