#+title: Gazette #BlueHats n°0
#+date: 2019-04-01
#+author: DINUM
#+layout: post
#+draft: false

Merci de vous être inscrits à la « gazette BlueHats » !

* blue hats, c'est qui ?

Les « blue hats » sont toutes les personnes qui souhaitent montrer
qu'elles contribuent à des logiciels libres développés et/ou utilisés
par l'administration publique : les agents publics impliqués dans le
développement de ces logiciels, bien sûr, mais aussi tout citoyen qui
reconnaît que son action pour des logiciels libres aide concrètement
des projets de l'administration.

Les « blue hats » portent des chapeaux bleus pour montrer leur
attachement à l'administration publique : il n'y a pas un unique
chapeau bleu, chacun invente le sien, il doit juste être bleu !

* Une gazette, pour quoi faire ?

La gazette « blue hats » est la contribution de la DINSIC au mouvement
blue hats.

Le but de cette lettre bimensuelle est de partager des informations
sur l'utilisation et le développement de logiciels libres dans et pour
l'administration.  Elle servira aussi à donner une vue d'ensemble des
activités du réseau de compagnonnage blue hats.  En la lisant, vous
découvrirez des projets que vous pourrez tester ou suivre ; en y
contribuant, vous partagerez vos initiatives et vos découvertes.

* Dois-je demander l'autorisation ?

Vous voulez organiser un événement blue hats ?  Faites-le et dites-le
nous !  Pas besoin d'autorisation.  Envoyez-nous les comptes-rendus de
vos ateliers et de vos événements, aussi modestes soient-ils, nous
pourrons les relayer via la gazette.

* S'approprier et faire évoluer la POCOS

La « POCOS » c'est le petit nom de la politique de contribution open
source de l'Etat, officielle depuis mai 2018.  Cette politique répond
à la question : en tant qu'agent public, comment puis-je contribuer à
un logiciel libre existant ou en publiant un nouveau logiciel libre ?

La version 1 de la POCOS est sortie en mai 2018, mais des corrections
sont toujours en cours, n'hésitez pas à faire les vôtres :

[[https://github.com/disic/politique-de-contribution-open-source/]]

Pour toute question : opensource@data.gouv.fr

* Le hackathon GLPI du ministère de l'Intérieur

GLPI est un logiciel libre de helpdesk destiné, entre autres, au suivi
de tâches ou de travaux.  Lundi 18 mars a eu lieu dans les locaux du
Ministère de l’Intérieur un hackathon interministériel pour rendre
l’interface de GLPI accessible aux personnes non voyantes.

Cette opération a eu lieu en présence d’experts de l’accessibilité
numérique et du RGAA, de développeurs, d’experts du produit GLPI et de
personnes non voyantes et expertes dans leurs outils d’accessibilité.
A l'exception d'une développeuse de la communauté GLPI, tous étaient
des agents de différentes administrations (DINSIC, Intérieur,
Préfecture, INSEE, Pôle Emploi, Éducation Nationale, etc.)

Cette journée a permis d’établir des constatations sur le code de
l’application, d’écrire un rapport sur ce produit et de tester
certaines modifications du code pour la rendre accessible. La
documentation du produit a aussi été évaluée et des correctifs ont été
appliqués.  La prochaine étape consistera à présenter ces travaux à
l’éditeur du produit afin qu’il implémente les correctifs, améliore la
qualité du code pour le rendre plus accessible, pour respecter les
référentiels d’accessibilité.

Ce hackathon était aussi l’occasion de découvrir cette forme de
travail collaboratif et de mettre les agents acteur de l’amélioration
de leurs outils de travail.  Pour les développeurs, c’était aussi le
moyen de comprendre certains mécanismes de l’accessibilité numérique
et d’être plus efficaces dans la mise en place de ces normes de
développement.

Nul doute que cette opération pourra se renouveler sur d’autres
logiciels avec une équipe encore plus soudée par cette expérience.
* La messagerie TCHAP présentée au FOSDEM

TCHAP est le nom de l'application basée sur Riot Matrix.  Une version
de TCHAP doit bientôt être disponible pour les agents publics.  Lors
du FOSDEM de février 2019, Matthew Hodgson a présenté l'utilisation
prochaine de Matrix par les administrations françaises :

[[https://matrix.org/blog/2019/02/04/matrix-at-fosdem-2019/]]

* L'Open Source Observatory évoque blue hats

L'open Source Observatory (OSOR) cite l'initiative blue hats dans leur
dernière lettre d'information.  Ils incitent les autres pays européens
à prendre exemple sur cette démarche communautaire pour renforcer la
place du libre dans les administrations publiques.

[[https://joinup.ec.europa.eu/news/les-blue-hats]]

* Le libre chez les Entrepreneurs d'intérêt général (EIG)

Le programme Entrepreneurs d'Intérêt Général permet à l'administration
de s'ouvrir à des talents du numérique pour résoudre des défis publics
en 10 mois.

La troisième promotion du programme réunit 32 datascientistes,
designers et développeurs autour de 15 défis.  Lors de son lancement
en février, les EIG et leurs mentors ont eu une présentation générale
de la place du logiciel libre dans les défis EIG :

[[https://speakerdeck.com/bluehats/les-logiciels-libres-dans-le-cadre-du-programme-entrepreneur-dinteret-general]]

Une présentation plus ciblée sur les enjeux autour de la publication
de logiciels libres par l'administration a été faite lors d'un atelier
EIG mi-mars :

[[https://speakerdeck.com/bluehats/du-logiciel-libre-ecrit-par-ladministration-publique]]

Pour un récit plus détaillé de la place du libre dans la promotion EIG
2018, vous pouvez lire cet article de blog :

[[https://entrepreneur-interet-general.etalab.gouv.fr/blog/2018/11/14/administrations-eig-et-logiciel-libre.html]]

* Les dépôts de codes sources d'organismes publics

Antoine Augusti, développeur à Etalab et EIG Link pour la troisième
promotion du programme Entrepreneur d'intérêt général a développé une
API exposant les métadonnées des dépôts de code source publiés par des
organismes publics.

[[https://github.com/etalab/data-codes-sources-fr]]

Prenez une minute pour vérifier que votre organisme public est bien
listé dans ce fichier et ouvrez une issue ou une pull request si ce
n'est pas le cas :

[[https://github.com/DISIC/politique-de-contribution-open-source/blob/master/comptes-organismes-publics]]

L'API doit continuer d'évoluer et voir s'adjoindre une interface de
navigation.

* Focus sur le Geotrek et Geonature

Témoignage de Camille Monchicourt, responsable du pôle Système
d’informations du Parc national des Écrins :

« Le Parc national des Écrins utilise des logiciels libres depuis de
nombreuses années. Pour y contribuer à notre tour, nous avons fait le
choix de publier nous aussi nos applications sous licence libre. Pour
cela, nous développons des outils génériques pour répondre à nos
besoins spécifiques, que ce soit pour des projets réalisés en interne
ou sous-traités. Au-delà du fait de publier nos développements sur une
forge sous licence libre, pour que ceux-ci soient réellement utilisés
et enrichis par d’autres structures, nous avons compris qu’il fallait
aussi les documenter, les illustrer, prendre du recul pour anticiper
d’autres contextes d’utilisation de nos outils, utiliser des
frameworks et standards, mais aussi présenter et communiquer sur ces
outils pour les faire connaître.  

C’est ainsi que nous avons construit des communautés avec aujourd'hui
plus de 100 structures utilisatrices de nos outils Geotrek et
GeoNature.  Nous animons ces communautés avec de l’information
régulière, des rencontres annuelles, des workshops, des groupes de
travail et de nombreux projets mutualisés »

Pour en savoir plus, lisez le retour sur le workshop GeoNature, outil
de gestion et de diffusion de données de biodiversité :

[[http://www.ecrins-parcnational.fr/actualite/geeks-geonature-carburent]]

* Invitez des blue hats !

Vous connaissez des personnes qui contribuent à des logiciels libres
développés ou utilisés dans l'administration ?  Offrez-leur un chapeau
bleu et invitez-les à s'inscrire à cette gazette !

[[https://infolettres.etalab.gouv.fr/subscribe/bluehats@mail.etalab.studio]]

* Une suggestion ? Une nouvelle à partager ?

Faites-nous en part en répondant tout simplement à ce message ou en
écrivant à bluehats@etalab.gouv.fr

Merci d'avance pour vos contributions !
